
DROP TABLE IF EXISTS `bc73q_sefurls`;
CREATE TABLE `bc73q_sefurls` (
  `id` int(11) NOT NULL,
  `cpt` int(11) NOT NULL DEFAULT '0',
  `sefurl` varchar(255) NOT NULL,
  `origurl` varchar(255) NOT NULL,
  `Itemid` varchar(20) DEFAULT NULL,
  `metadesc` varchar(255) DEFAULT '',
  `metakey` varchar(255) DEFAULT '',
  `metatitle` varchar(255) DEFAULT '',
  `metalang` varchar(30) DEFAULT '',
  `metarobots` varchar(30) DEFAULT '',
  `metagoogle` varchar(30) DEFAULT '',
  `metacustom` text,
  `metaauthor` varchar(30) DEFAULT '',
  `canonicallink` varchar(255) DEFAULT '',
  `dateadd` date NOT NULL DEFAULT '0000-00-00',
  `priority` int(11) NOT NULL DEFAULT '0',
  `trace` text,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `locked` tinyint(1) NOT NULL DEFAULT '0',
  `sef` tinyint(1) NOT NULL DEFAULT '1',
  `sm_indexed` tinyint(1) NOT NULL DEFAULT '0',
  `sm_date` date NOT NULL DEFAULT '0000-00-00',
  `sm_frequency` varchar(20) NOT NULL DEFAULT 'weekly',
  `sm_priority` varchar(10) NOT NULL DEFAULT '0.5',
  `flag` tinyint(1) NOT NULL DEFAULT '0',
  `host` varchar(255) NOT NULL DEFAULT '',
  `showsitename` int(1) NOT NULL DEFAULT '3'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `bc73q_sefurls` VALUES(1, 0, 'nas-tym/o-nas/our-advantages/rss', 'index.php?option=com_content&format=feed&id=67&layout=theme3447:category&type=rss&view=category', '701', '', '', '', '', '', '', NULL, '', '', '2017-12-12', 35, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(2, 0, 'nas-tym/o-nas/our-advantages/atom', 'index.php?option=com_content&format=feed&id=67&layout=theme3447:category&type=atom&view=category', '701', '', '', '', '', '', '', NULL, '', '', '2017-12-12', 35, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(3, 10, 'ochrana-soukromi/podminky-uziti', 'index.php?option=com_content&id=10&layout=theme3447:category&view=category', '176', 'Ochrana osobních údajů web - fyzioterapie Praha 9, Horní Počernice', 'ochrana osobních údajů, Horní Počernice', '', '', '', '', NULL, '', '', '2017-12-12', 35, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(4, 10, 'centrum-fyzioterapie-praha/o-nas', 'index.php?option=com_content&id=9&layout=theme3447:category&view=category', '134', 'O společnosti - fyzioterapie Praha 9, Horní Počernice', 'fyzioterapeut Praha 9, fyzioterapeut Praha Horní Počernice', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 35, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(5, 9, 'nas-tym/o-nas/prednosti', 'index.php?option=com_content&id=67&layout=theme3447:category&view=category', '701', '', '', '', '', '', '', NULL, '', '', '2017-12-12', 35, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(6, 201, '', 'index.php?option=com_content&id=8&layout=theme3447:category&view=category', '101', '', '', '', '', '', '', NULL, '', '', '2017-12-12', 90, NULL, 1, 1, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(7, 0, 'nas-tym/kinisi-fyzioterapie-logo', 'index.php?option=com_content&catid=2&id=144&view=article', '701', 'Centrum fyzioterapie Kinisi, Praha 9 - Horní Počernice spojuje profesionální přístup zkušených fyzioterapeutů se špičkovým moderním vybavením.', 'Centrum fyzioterapie Kinisi, Praha 9 - Horní Počernice, fyzioterapeut Praha Horní Počernice, fyzioterapeut Praha 9', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(8, 0, 'reference/reference-technology-florbal-mlada-boleslav', 'index.php?option=com_content&catid=66&id=151&view=article', '701', 'Reference na Mgr. Vojtoviče z fyzioterapeutického centra Kinisi v Praze 9, Horních Počernicích - Technology Florbal MB', 'hlavní, mgr, fyzioterapie, sezóny, kinisi, vojtovič, podílí, zdravotně-kondiční', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(9, 0, 'reference/acema-sparta-praha-florbal', 'index.php?option=com_content&catid=66&id=152&view=article', '701', 'Reference na Bc. M. Hrickovou z fyzioterapeutického centra Kinisi v Praze 9, Horní Počernice - ACEMA Sparta Praha Florbal', 'business, key, members, operation, significant, aspect, organization, high', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(10, 0, 'eference/reference-vanecek', 'index.php?option=com_content&catid=66&id=153&view=article', '701', 'Fyzioterapeutické centrum Kinisi v Horních Počernicích získává stále více pozitivních hodnocení od svých klientů.', 'business, key, members, operation, significant, aspect, organization, high', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(11, 0, 'reference-fyzioterapie-kinisi-praha', 'index.php?option=com_content&catid=2&id=177&view=article', '137', 'Reference na Centrum fyzioterapie v Horních Počernicích, Praha 9', '', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(12, 6, 'nas-tym/tym-fyzioterapie-kinisi/fyzioterapeutka-hrickova', 'index.php?option=com_content&catid=26&id=44&view=article', '701', 'Fyzioterapeutka Kinisi, Praha 9 - Horní Počernice vedle sportovců pracuje s dospělými, dětmi od 2 let a neurologickými pacienty.', 'studia, kde, vedené, komplexně, pacienty, zakládá, neurologickými, sportovců', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(13, 2, 'nas-tym/tym-fyzioterapie-kinisi/mgr-martin-vojtovic', 'index.php?option=com_content&catid=26&id=46&view=article', '701', 'Výborný fyzioterapeut Kinisi, Praha 9 - Horní Počernice se specializuje zejména na sportovní fyzioterapii a funkční trénink.', 'Fyzioterapeut Mgr. Martin Vojtovič, Fyzioterapeut Praha 9, Fyzioterapeut Praha 8, Fyzioterapeut Horní Počernice', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(14, 6, 'nas-tym/tym-fyzioterapie-kinisi/fyzioterapeutka-augustinova', 'index.php?option=com_content&catid=26&id=45&view=article', '701', 'Úspěšná fyzioterapeutka poskytující služby fyzioterapeuta v Kinisi, Praha 9 - Horní Počernice', 'Tým Kinisi Centrum Fyzioterapie, společnost fyzioterapie Praha 9 Horní Počernice, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(15, 16, 'sluzby-a-programy/fyzioterapie-dospelych', 'index.php?option=com_content&catid=83&id=227&view=article', '681', 'V pražském centru Kinisi vybíráme postup léčby ze široké škály metod a terapeutických prostředků individuálně podle potřeby každého klienta.', 'výborný fyzioterapeut Praha, soukromý fyzioterapeut, typ na fyzioterapeuta Praha', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(16, 18, 'sluzby-a-programy/fyzioterapie-dospelych/fyzioterapeuticke-vysetreni-dospelych', 'index.php?option=com_content&catid=84&id=192&view=article', '656', 'Používané metody a terapeutické přístupy ve fyzioterapii dospělých v centru fyzioterapie Praha 9', 'výborný fyzioterapeut Praha, fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(17, 28, 'sluzby-a-programy/fyzioterapie-dospelych/indikace', 'index.php?option=com_content&catid=84&id=193&view=article', '657', 'APoužívané metody a terapeutické přístupy ve fyzioterapii dospělých v centru', 'dddd', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(18, 16, 'sluzby-a-programy/fyzioterapie-dospelych/metody-a-terapeuticke-pristupy-ve-fyzioterapii-dospelych', 'index.php?option=com_content&catid=84&id=194&view=article', '658', 'Používané metody a terapeutické přístupy ve fyzioterapii dospělých v centru fyzioterapie Kinisi na Praze 9', 'integrace, stimulace, primitivních, reflexů	synergická, reflexní, 	senzomotorická, dns, podle', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(19, 1, 'sluzby-a-programy/detska-fyzioterapie', 'index.php?option=com_content&catid=83&id=226&view=article', '682', 'Posláním fyzioterapeutů v pražském centru Kinisi je zachytit a ovlivnit v co nejmladším věku  odchylky ve vývoji dítěte.', 'odchylky, vývoji, dítěte, ovlivnit, zachytit, fyzioterapeutů, centru, kinisi', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(20, 0, 'sluzby-a-programy/detska-fyzioterapie/vysetreni-v-detske-fyzioterapii', 'index.php?option=com_content&catid=88&id=195&view=article', '664', 'Komplexní fyzioterapeutické vyšetření u dětí ve věku 5–18 let je zaměřeno na řešení akutních i chronických obtíží pohybového systému.', 'jsou, pohybového, které, dítěte, vyšetření, systému, při, věku', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(21, 1, 'sluzby-a-programy/detska-fyzioterapie/indikace-v-detske-fyzioterapii', 'index.php?option=com_content&catid=88&id=196&view=article', '665', 'AIndikace v dětské fyzioterapii, které se věnujeme ve fyzioterapeutickém centru Kinisi v Praze 9', 'korekce, poruchou, jako, stavy, péče, kloubů,  , pozornosti', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(22, 0, 'sluzby-a-programy/detska-fyzioterapie/metody-a-terapeuticke-pristupy-v-detske-fyzioterapii', 'index.php?option=com_content&catid=88&id=197&view=article', '666', 'V Kinisi využíváme mezinárodně uznávané vědecké metody, které respektují neurofyhybziologické principy lidského těla a pou.', 'dns, \r\n	senzomotorická, stimulace, koláře, pavla, podle, prof, \r\n	integrace', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(23, 1, 'sluzby-a-programy/fyzioterapie-pro-zeny', 'index.php?option=com_content&catid=83&id=225&view=article', '685', 'Zaměřujeme se na ženy toužící otěhotnět, ženy, které mají v těhotenství potíže s pohybovým aparátem nebo se chtějí udržovat v dobré fyzické kondici.', 'také, ženy, posílit, břišní, zádové, dna, pánevního, svalů', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(24, 1, 'sluzby-a-programy/fyzioterapie-pro-zeny/lecba-funkcni-sterility', 'index.php?option=com_content&catid=99&id=204&view=article', '672', 'V fyzioterapeutickém centru v Horních Počernicích v Praze se specializujeme se  na funkční sterilitu.', 'při, pánevního, oblasti, svalů, cvičení, ošetření, dna, napětí', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(25, 4, 'sluzby-a-programy/fyzioterapie-pro-zeny/fyzioterapie-v-tehotenstvi', 'index.php?option=com_content&catid=99&id=205&view=article', '673', 'Přiměřený pohyb je základem správné životosprávy v těhotenství a jeho záměrem je udržet budoucí maminky v co nejlepší fyzické a psychické kondici.', 'svaly, těhotenství, vzniku, pro, dochází, také, cvičení, systému', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(26, 0, 'sluzby-a-programy/fyzioterapie-pro-zeny/fyzioterapie-po-porodu', 'index.php?option=com_content&catid=99&id=206&view=article', '674', 'Po nekomplikovaném porodu žena začíná cvičit po 12-24 hodinách. Hlavním cílem cvičení je povzbudit krevní oběh a předejít tak tromboembolické nemoci.', 'cvičení, svalů, dělohy, dle, také, pánevního, správnou, zavinování', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(27, 1, 'sluzby-a-programy/akutni-a-pooperacni-fyzioterapie', 'index.php?option=com_content&catid=83&id=230&view=article', '683', 'V Kinisi se zaměřujeme na  akutní bolesti pohybového systému a pooperační fyzioterapii', 'fyzioterapie, akutní, bolesti, zachování, obnova, otoku, plného, pohybu', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(28, 0, 'akutni-fyzioterapie/sluzby-a-programy/akutni-a-pooperacni-fyzioterapie/lecba-urazu-a-akutnich-bolestivych-blokad', 'index.php?option=com_content&catid=92&id=198&view=article', '667', 'V fyzioterapeutickém centru v Horních Počernicích v Praze poskytujeme klientům akutní fyzioterapii', 'bolesti, akutní, blokády, akutních, kloubů, nebo, fyzioterapie, blokáda', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(29, 0, 'sluzby-a-programy/akutni-a-pooperacni-fyzioterapie/pooperacni-pece-a-lecba', 'index.php?option=com_content&catid=92&id=200&view=article', '668', 'V fyzioterapeutickém centru v Horních Počernicích v Praze poskytujeme klientům V fyzioterapeutickém centru v Horních Počernicích v Praze poskytujeme klientům předoperační léčbu a pooperační péči', 'operaci, páteře, využíváme, také, pohybu, tkání, pooperační, rozsahu', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(30, 0, 'sluzby-a-programy/funkcni-fyziotrenink', 'index.php?option=com_content&catid=83&id=229&view=article', '684', 'Naším cílem je dijít k efektivní účelné svalové aktivaci, zvýšení sportovní výkonnosti, menšímu opotřebení pohybového systému a kompenzaci stresové zátěže.', 'opotřebení, pohybového, systému, menšímu, výkonnosti, aktivaci, zvýšení, sportovní', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(31, 0, 'sluzby-a-programy/funkcni-fyziotrening/preventivni-programy-ve-funkcnim-fyziotreninku', 'index.php?option=com_content&catid=95&id=201&view=article', '669', 'Ve spolupráci s fyzioterapeutem Mgr. Martinem Vojtovičem jsme v Kinisi vypracovali speciální preventivní program pro vrcholové i amatérské sportovce.', 'program, následně, rámci, plán, pohybového, preventivní, cvičení, aby', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(32, 0, 'sluzby-a-programy/funkcni-fyziotrening/spravne-cviceni-a-posilovani', 'index.php?option=com_content&catid=95&id=202&view=article', '670', 'Předpokladem správného posilování je porozumění vlastnímu tělu,  součástí tréninku by měli být techniky  na uvědomění tělesných částí a pohybů.', 'sportu, např, tak, posilování, správného, konkrétním, zlepšit, pohybového', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(33, 0, 'sluzby-a-programy/funkcni-fyziotrening/metody-a-treninkove-prostredky-funkcniho-fyziotreningu', 'index.php?option=com_content&catid=95&id=203&view=article', '671', 'Metody a tréninkové prostředky funkčního fyziotréningu', 'flowin\r\n\r\n&nbsp, aguahit\r\n\r\n&nbsp, bosu\r\n\r\n\r\n\r\n&nbsp, thera-band\r\n\r\n\r\n\r\n&nbsp, blackroll\r\n\r\n&nbsp, gymball, spine\r\n\r\n&nbsp, sliding', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(34, 0, 'sluzby-a-programy/pece-o-sportovce', 'index.php?option=com_content&catid=83&id=228&view=article', '686', 'V pražském centru v Horních Počernicích se specializujeme na sportovní fyzioterapii a péčí o sportovce.', 'analýza, vzorů, pohybových, sportovců, bezpečný, návrat, sportovce, nejrychlejší', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(35, 0, 'sluzby-a-programy/pece-o-sportovce/komplexni-analyza-sportovce', 'index.php?option=com_content&catid=100&id=211&view=article', '675', 'Účelem testování je zjistit, kde bolest nebo dysfunkce vzniká, aby bylo možné předepsat specifickou léčbu a obnovit fyziologické vzorce pohybu sportovce.', 'nebo, sportovce, dysfunkce, testování, při, výkonnosti, specifickou, být', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(36, 0, 'sluzby-a-programy/pece-o-sportovce/indikace-sportovni-fyzioterapie', 'index.php?option=com_content&catid=100&id=207&view=article', '676', 'AV fyzioterapeutickém centru v Horních Počernicích v Praze se specializujeme na sportovní fyzioterapii.', 'fyzioterapeut Praha Horní Počernice', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(37, 0, 'sluzby-a-programy/pece-o-sportovce/lecba-akutnich-urazu-sportovcu', 'index.php?option=com_content&catid=100&id=208&view=article', '678', 'Cílem fyzioterapie v léčbě akutních úrazů a poranění sportovců je, aby se sportovec mohl co nejdřív vrátit ke sportovní aktivitě.', 'léčba, \r\n\r\n&nbsp, ultrazvuk, tdp, suchou, fyzioterapie, rozsahu, měkké', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(38, 0, 'sluzby-a-programy/pece-o-sportovce/preventivni-programy-sportovcu', 'index.php?option=com_content&catid=100&id=209&view=article', '677', 'Ve spolupráci s fyzioterapeutem Mgr. Martinem Vojtovičem jsme v Kinisi, Praha 9 vypracovali speciální preventivní program sportovců s cvičebně-terapeutickým plánem.', 'následně, terapii, svalů, cvičení, pohybového, rámci, sekvencí, základem', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(39, 0, 'sluzby-a-programy/pece-o-sportovce/metody-a-terapeuticke-pristupy-u-sportovcu', 'index.php?option=com_content&catid=100&id=210&view=article', '679', 'Metody a terapeutické přístupy u sportovců ve fyzioterapeutickém centru v Horních Počernicích v Praze', 'lampou\r\n	kineziotaping\r\n\r\n\r\n\r\n\r\n\r\n	metoda, tdp, jehlou\r\n	léčba, suchou, ludmily, mojžíšové\r\n	trénink, elektroléčba, stimulace\r\n	ultrazvuk', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(40, 8, 'DNS-podle-prof-pavla-kolare/metody-a-lecebne-pristupy/DNS', 'index.php?option=com_content&catid=101&id=215&view=article', '689', 'V pražském centru fyzioterapie Kinisi využíváme koncept DNS podle Prof. Koláře (DNS) - přístup založený na vývojové kineziologii.', 'svalů, břišních, zapojení, postavení, dns, terapie, symetrii, také', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(41, 0, 'metody-a-lecebne-pristupy/metoda-ludmily-mojzisove-v-nasem-fyzioterapeutickem-centru', 'index.php?option=com_content&catid=101&id=220&view=article', '692', 'Využíváme speciální manuální techniku Ludmily Mojžíšové, která vede k  odstranění chybných strukturálních a funkčních změn na pohybovém systému.', '&nbsp, při, žeber, klienta, pánevního, metody, dna, bolesti', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(42, 0, 'metody-a-lecebne-pristupy/senzomotoricka-stimulace', 'index.php?option=com_content&catid=101&id=216&view=article', '690', 'Nácvik stability osového systému a korekce příčně i podélně ploché nohy s využitím moderních balančních pomůcek (bosu, flowin, TRX, gymball, stepper, aquahit, theraband, overball, blackroll).\r\n\r\nSenzomotorická stimulace představuje vzájemnou', 'pohybového, informací, pomůcek, při, terapii, využívá, balančních, pacienta', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(43, 0, 'metody-a-lecebne-pristupy/integrace-primitivnich-reflexu', 'index.php?option=com_content&catid=101&id=217&view=article', '691', 'Za pomoci integrace primitivních reflexů dochází k upevnění a zlepšení pohybových vzorů, což napomáhá ke zlepšování motorických dovedností.', 'vývoj, reflexy, ale, jejich, jsou, psychický, pohyby, dítěte', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(44, 0, 'metody-a-lecebne-pristupy/synergicka-reflexni-terapie-srt', 'index.php?option=com_content&catid=101&id=219&view=article', '697', 'Ve fyzioterapeutickém centru využíváme speciální manuální techniku STR vedoucí k odstranění chybných strukturálních a funkčních změn na pohybovém systému.', 'poruchy, mozková, pooperační, jako, stavy, techniky, vrozené, vady', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(45, 0, 'metody-a-lecebne-pristupy/lecba-suchou-jehlou-dry-needling', 'index.php?option=com_content&catid=101&id=221&view=article', '693', 'Terapie suchou jehlou spočívá v aplikaci suché jehly do spoušťového bolestivého bodu, čímž  ve svalu dochází k výraznému analgetickému účinku.', 'bolesti, terapie, loket, bolestivé, suchou, při, aplikovat, daného', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(46, 0, 'metody-a-lecebne-pristupy/vyuziti-metody-kineziotapingu', 'index.php?option=com_content&catid=101&id=222&view=article', '694', 'V pražském fyzioteraputickém centru Kinisi využíváme metodu kineziotapingu, které se dostává velké obliby ve sportovní sféře i mimo ni.', '&nbsp, bolesti, pásky, akutní, patologie, kůži, pro, oblasti', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(47, 2, 'metody-a-lecebne-pristupy/ultrazvuk-a-elektroterapie', 'index.php?option=com_content&catid=101&id=223&view=article', '695', 'Přístrojovou terapii využíváme pro vyhledávání a odstraňování reflexních spoušťových bodů – trigger points, posttraumatické bolesti (výrony, hematomy, zlomeniny), revmatické nebo artrotické bolesti.\r\n\r\n\r\n\r\nElektroléčba\r\n\r\nje část fyzikální terapie,', 'bolesti, &nbsp, při, vlnění, nebo, terapie, pod, aplikace', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(48, 18, 'metody-a-lecebne-pristupy/lecba-tdp-lampou-ve-fyzioterapii', 'index.php?option=com_content&catid=101&id=224&view=article', '696', 'Lampu TDT v našem fyzioterapeutickém centru Kinisi v Praze 9  využíváme především pro relaxaci svalů před mobilizací při bolestech páteře.', 'Léčba TDP lampou, akutní bolet zad terapie, akutní bolet zad léčba', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(49, 11, 'cenik-sluzeb/fyzioterapie-dospelych', 'index.php?option=com_content&id=35&layout=theme3447:category&view=category', '639', '', '', '', '', '', '', NULL, '', '', '0000-00-00', 35, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(50, 2, 'ceny-detska-fyzioterapie/cenik-sluzeb/detska-fyzioterapie', 'index.php?option=com_content&id=77&layout=theme3447:category&view=category', '640', '', '', '', '', '', '', NULL, '', '', '0000-00-00', 35, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(51, 6, 'fyzioterapie-clanky-a-informace/clanky', 'index.php?option=com_content&filter_tag[0]=&id=11&layout=blog&view=category', '285', '', '', '', '', '', '', NULL, '', '', '0000-00-00', 55, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(52, 8, 'fyzioterapie-praha-kontakt/website-administrators/fyzioterapeuticke-centrum-kinisi', 'index.php?option=com_contact&id=1&view=contact', '142', '\'Website Administrators\' contact category description. Ut sapien enim, rhoncus sit amet fermentum at, sagittis ac massa. Fusce quis odio sit amet ipsum gravida faucibus vel et turpis. Aliquam a dui pretium elit feugiat interdum. Suspendisse tortor', 'amet, sit, sagittis, quis, ipsum, aliquam, integer, dictum', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(53, 0, 'pozadavek-pripomenuti-jmeno/zapomenute-heslo', 'index.php?option=com_users&view=reset', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(54, 0, 'pozadavek-pripomenuti-jmeno/zapomenute-jmeno', 'index.php?option=com_users&view=remind', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(55, 0, 'pozadavek-pripomenuti-jmeno/registrace', 'index.php?option=com_users&view=registration', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(56, 0, 'kinisi-fyzioterapie-hp/kinisi/rss', 'index.php?option=com_content&format=feed&id=8&layout=theme3447:category&type=rss&view=category', '101', '', '', '', '', '', '', NULL, '', '', '0000-00-00', 35, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(57, 0, 'kinisi-fyzioterapie-hp/kinisi/atom', 'index.php?option=com_content&format=feed&id=8&layout=theme3447:category&type=atom&view=category', '101', '', '', '', '', '', '', NULL, '', '', '0000-00-00', 35, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(58, 21, 'clanky/posledni/svaly-okolo-kolena-by-mel-posilovat-kazdy', 'index.php?option=com_content&catid=15&id=10&view=article', '101', 'YYY Když svaly ochabnou, kloub je náchylnější na zranění, kolena se vyplatí procvičovat.', 'jsou, břicho, kolena, které, \", dostat, kloubů, kondice', '', '', '', '', 'a:0:{}', '', '', '2017-12-12', 90, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(59, 21, 'clanky/posledni/fyzioterapeutuv-sen-plazovy-fotbal', 'index.php?option=com_content&catid=15&id=13&view=article', '101', 'CCC Plážový volejbal je velice prospěšný pro náš pohybový systém.', 'bublina', '', '', '', '', NULL, '', '', '2017-12-11', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(60, 2, 'clanky/posledni/maminky-pozor-na-zatezovani-kloubu-a-svalu', 'index.php?option=com_content&catid=15&id=190&view=article', '101', 'Co dělat, aby maminky fyzicky zvládaly své mateřství? Na dotaz odpovídala Lenka Augustínová z našeho centra v Praze na servru Výhra na sedm.cz.', 'páteř, cvik, před, sebou, aby, které, ruce, mohou', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(61, 0, 'fyzioterapie-sluzby/fyzioterapie-dospelych', 'index.php?option=com_content&catid=18&id=16&view=article', '101', 'V pražském centru Kinisi vybíráme postup léčby ze široké škály metod a terapeutických protředků individuálně podle potřeby každého klienta.', 'pohybů, tak, aby, normalizace, obnovení, cílem, nedocházelo, přetížení', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(62, 0, 'fyzioterapie-sluzby/detska-fyzioterapie', 'index.php?option=com_content&catid=18&id=17&view=article', '101', 'Posláním fyzioterapeutů v pražském centru Kinisi je zachytit a ovlivnit v co nejmladším věku  odchylky ve vývoji dítěte.', 'odchylky, vývoji, dítěte, ovlivnit, zachytit, fyzioterapeutů, centru, kinisi', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(63, 0, 'fyzioterapie-sluzby/fyzioterapie-zeny', 'index.php?option=com_content&catid=18&id=167&view=article', '101', 'Zaměřujeme se na ženy toužící otěhotnět, ženy, které mají v těhotenství potíže s pohybovým aparátem nebo se chtějí udržovat v dobré fyzické kondici.', 'také, ženy, posílit, břišní, zádové, dna, pánevního, svalů', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(64, 0, 'fyzioterapie-sluzby/akutni-a-pooperacni-fyzioterapie', 'index.php?option=com_content&catid=73&id=18&view=article', '101', 'V Kinisi se zaměřujeme na  akutní bolesti pohybového systému a pooperační fyzioterapii', 'fyzioterapie, akutní, bolesti, zachování, obnova, otoku, plného, pohybu', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(65, 0, 'fyzioterapie-sluzby/funkcni-fyziotrenink', 'index.php?option=com_content&catid=73&id=166&view=article', '101', 'Naším cílem je dijít k efektivní účelné svalové aktivaci, zvýšení sportovní výkonnosti, menšímu opotřebení pohybového systému a kompenzaci stresové zátěže.', 'opotřebení, pohybového, systému, menšímu, výkonnosti, aktivaci, zvýšení, sportovní', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(66, 0, 'fyzioterapie-sluzby/pece-o-sportovce', 'index.php?option=com_content&catid=73&id=168&view=article', '101', 'V pražském centru v Horních Počernicích se specializujeme na sportovní fyzioterapii a péčí o sportovce.', 'analýza, vzorů, pohybových, sportovců, bezpečný, návrat, sportovce, nejrychlejší', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(67, 0, 'oteviraci-hodiny', 'index.php?option=com_content&catid=63&id=137&view=article', '101', 'Rádi Vás uvítáme v našem fyzioterapeutickém centru v Praze - Horních Počernicích\r\n\r\n\r\nDomluvit si termín', 'horních, počernicích\r\n\r\n\r\ndomluvit, termín, praze, centru, vás, uvítáme, našem', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(68, 0, 'individualni-pece', 'index.php?option=com_content&catid=63&id=138&view=article', '101', 'Každý zdravotní stav nebo zranění je individuální. Naši péči přizpůsobujeme přesně vašim potřebám.\r\n\r\n\r\nZjistit o Kinisi více', 'vašim, přesně, přizpůsobujeme, potřebám, \r\n\r\n\r\nzjistit, více, kinisi, péči', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(69, 0, 'budte-v-kondici', 'index.php?option=com_content&catid=63&id=165&view=article', '101', 'Pomůžeme vám vyřešit současný problém a zabránit jeho návratu\r\n\r\n\r\nKontaktovat', 'zabránit, jeho, návratu\r\n\r\n\r\nkontaktovat, problém, současný, vám, vyřešit, pomůžeme', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(70, 0, 'fyzioterapie-clanky-a-informace/clanky/rss', 'index.php?option=com_content&filter_tag[0]=&format=feed&id=11&layout=blog&type=rss&view=category', '285', '', '', '', '', '', '', NULL, '', '', '0000-00-00', 55, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(71, 0, 'fyzioterapie-clanky-a-informace/clanky/atom', 'index.php?option=com_content&filter_tag[0]=&format=feed&id=11&layout=blog&type=atom&view=category', '285', '', '', '', '', '', '', NULL, '', '', '0000-00-00', 55, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(72, 1, 'tagy/media', 'index.php?option=com_tags&id=12&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 1, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(73, 0, 'tagy/klouby', 'index.php?option=com_tags&id=21&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 1, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(74, 0, 'tagy/svaly', 'index.php?option=com_tags&id=25&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 1, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(75, 0, 'tagy/brisni-svaly', 'index.php?option=com_tags&id=22&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 1, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(76, 0, 'tagy/fyzioterapie-pro-zeny', 'index.php?option=com_tags&id=19&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 1, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(77, 0, 'tagy/cviceni-s-detmi', 'index.php?option=com_tags&id=20&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 1, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(78, 0, 'tagy/dulezite', 'index.php?option=com_tags&id=10&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 1, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(79, 2, 'kinisi-fyzioterapie-hp/uncategorised/kinisi-fyzioterapie-logo/upravit', 'index.php?option=com_content&a_id=144&catid=2&id=0&task=article.edit&view=article', '101', 'Centrum fyzioterapie Kinisi, Praha 9 - Horní Počernice spojuje profesionální přístup zkušených fyzioterapeutů se špičkovým moderním vybavením.', 'Centrum fyzioterapie Kinisi, Praha 9 - Horní Počernice, fyzioterapeut Praha Horní Počernice, fyzioterapeut Praha 9', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(80, 8, 'clanky/posledni/svaly-okolo-kolena-by-mel-posilovat-kazdy/upravit', 'index.php?option=com_content&a_id=10&catid=15&id=10&task=article.edit&view=article', '101', 'Když svaly ochabnou, kloub je náchylnější na zranění, kolena se vyplatí procvičovat.', 'jsou, břicho, kolena, které, \", dostat, kloubů, kondice', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(81, 10, 'clanky/posledni/fyzioterapeutuv-sen-plazovy-fotbal/upravit', 'index.php?option=com_content&a_id=13&catid=15&id=13&task=article.edit&view=article', '101', 'CCC Plážový volejbal je velice prospěšný pro náš pohybový systém.', 'bublina', '', '', '', '', NULL, '', '', '2017-12-11', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(82, 0, 'clanky/posledni/maminky-pozor-na-zatezovani-kloubu-a-svalu/upravit', 'index.php?option=com_content&a_id=190&catid=15&id=190&task=article.edit&view=article', '101', 'Co dělat, aby maminky fyzicky zvládaly své mateřství? Na dotaz odpovídala Lenka Augustínová z našeho centra v Praze na servru Výhra na sedm.cz.', 'páteř, cvik, před, sebou, aby, které, ruce, mohou', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(83, 4, 'tym-fyzioterapie-kinisi/fyzioterapeutka-hrickova/upravit', 'index.php?option=com_content&a_id=44&catid=26&id=44&task=article.edit&view=article', '101', 'Fyzioterapeutka Kinisi, Praha 9 - Horní Počernice vedle sportovců pracuje s dospělými, dětmi od 2 let a neurologickými pacienty.', 'studia, kde, vedené, komplexně, pacienty, zakládá, neurologickými, sportovců', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(84, 2, 'kinisi-fyzioterapie-hp/stranky/tym-fyzioterapie-kinisi/mgr-martin-vojtovic/upravit', 'index.php?option=com_content&a_id=46&catid=26&id=46&task=article.edit&view=article', '101', 'Výborný fyzioterapeut Kinisi, Praha 9 - Horní Počernice se specializuje zejména na sportovní fyzioterapii a funkční trénink.', 'Fyzioterapeut Mgr. Martin Vojtovič, Fyzioterapeut Praha 9, Fyzioterapeut Praha 8, Fyzioterapeut Horní Počernice', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(85, 0, 'tym-fyzioterapie-kinisi/fyzioterapeutka-augustinova/upravit', 'index.php?option=com_content&a_id=45&catid=26&id=45&task=article.edit&view=article', '101', 'Úspěšná fyzioterapeutka poskytující služby fyzioterapeuta v Kinisi, Praha 9 - Horní Počernice', 'Tým Kinisi Centrum Fyzioterapie, společnost fyzioterapie Praha 9 Horní Počernice, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(86, 49, '404/uncategorised/404', 'index.php?option=com_content&catid=2&id=65&view=article', '204', 'OMLOUVÁME SE,STRÁNKA NEBYLA NALEZENABohužel, stránku, na kterou jste vstoupili nemůžeme najít. Vraťte se prosím na domácí stránku, zkuste vyhledávání nebo se nám rovnou ozvěte a společně najdeme to, co hledáte. S námi se možná  dozvíte', 'jste, najít, stránku, informací, námi, než, víc, možná ', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(87, 0, '404/uncategorised/404/upravit', 'index.php?option=com_content&a_id=65&catid=2&id=65&task=article.edit&view=article', '204', 'OMLOUVÁME SE,STRÁNKA NEBYLA NALEZENABohužel, stránku, na kterou jste vstoupili nemůžeme najít. Vraťte se prosím na domácí stránku, zkuste vyhledávání nebo se nám rovnou ozvěte a společně najdeme to, co hledáte. S námi se možná  dozvíte', 'jste, najít, stránku, informací, námi, než, víc, možná ', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(88, 0, 'nas-tym', 'index.php?option=com_content&id=43&view=category', '701', '', '', '', '', '', '', NULL, '', '', '0000-00-00', 35, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(89, 0, 'tym-fyzioterapie-kinisi', 'index.php?option=com_content&id=26&view=category', '701', '&nbsp;', '&nbsp', '', '', '', '', NULL, '', '', '0000-00-00', 35, NULL, 1, 1, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(90, 2, 'pozadavek-pripomenuti-jmeno/prihlasit', 'index.php?option=com_users&view=login', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(91, 2, 'pozadavek-pripomenuti-jmeno/uzivatel/prihlasit', 'index.php?option=com_users&task=user.login', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(92, 1, 'kinisi-fyzioterapie-hp/podminky-uziti/podminky-uziti', 'index.php?option=com_content&catid=10&id=6&view=article', '101', 'Autorská právaVlastníkem a provozovatelem internetových stránek kinisi.cz je společnost Kinisi, s.r.o. Centrum fyziotarpie, která je oprávněna vykonávat majetková práva k těmto internetovým stránkám (dále jen', 'stránek, těchto, uživatel, provozovatel, stránkách, stránky, cookies, provozovatele', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(93, 0, 'centrum-fyzioterapie-praha/o-nas/rss', 'index.php?option=com_content&format=feed&id=9&layout=theme3447:category&type=rss&view=category', '134', '', '', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 35, NULL, 1, 0, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(94, 0, 'centrum-fyzioterapie-praha/o-nas/atom', 'index.php?option=com_content&format=feed&id=9&layout=theme3447:category&type=atom&view=category', '134', '', '', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 35, NULL, 1, 0, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(95, 0, 'centrum-fyzioterapie-praha/hp-reference/reference-technology-florbal-mlada-boleslav/upravit', 'index.php?option=com_content&a_id=151&catid=66&id=151&task=article.edit&view=article', '134', 'Reference na Mgr. Vojtoviče z fyzioterapeutického centra Kinisi v Praze 9, Horních Počernicích - Technology Florbal MB', 'hlavní, mgr, fyzioterapie, sezóny, kinisi, vojtovič, podílí, zdravotně-kondiční', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(96, 0, 'centrum-fyzioterapie-praha/hp-reference/acema-sparta-praha-florbal/upravit', 'index.php?option=com_content&a_id=152&catid=66&id=152&task=article.edit&view=article', '134', 'Reference na Bc. M. Hrickovou z fyzioterapeutického centra Kinisi v Praze 9, Horní Počernice - ACEMA Sparta Praha Florbal', 'business, key, members, operation, significant, aspect, organization, high', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(97, 0, 'centrum-fyzioterapie-praha/hp-reference/reference-vanecek/upravit', 'index.php?option=com_content&a_id=153&catid=66&id=153&task=article.edit&view=article', '134', 'Fyzioterapeutické centrum Kinisi v Horních Počernicích získává stále více pozitivních hodnocení od svých klientů.', 'business, key, members, operation, significant, aspect, organization, high', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(98, 0, 'centrum-fyzioterapie-praha/o-nas/kvalita-sluzeb-3/kvalita-sluzeb', 'index.php?option=com_content&catid=71&id=157&view=article', '134', 'V Centru fyzioterapie v Horních Počernicích, Praha 9 se setkáte s moderním prostředím a vysokou kvalitou služeb.', 'postupů, nejmodernějších, využití, technologií, garantujeme, informací, veškerých, důvěrnost', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(99, 2, 'centrum-fyzioterapie-praha/o-nas/kvalita-sluzeb-3/kvalita-sluzeb/upravit', 'index.php?option=com_content&a_id=157&catid=71&id=157&task=article.edit&view=article', '134', 'V Centru fyzioterapie v Horních Počernicích, Praha 9 se setkáte s moderním prostředím a vysokou kvalitou služeb.', 'postupů, nejmodernějších, využití, technologií, garantujeme, informací, veškerých, důvěrnost', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(100, 0, 'centrum-fyzioterapie-praha/o-nas/kvalita-sluzeb-4/individualni-pristup', 'index.php?option=com_content&catid=72&id=163&view=article', '134', 'V Centru fyzioterapie v Horních Počernicích, Praha 9 ke každému klientovi přistupujeme individuálně od diagnostiky, plánu léčby po jednotlivá sezení. ', 'případě, zachováváme, přístup, individuální, léčebného/preventivního, programu, cvičení, skupinové', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(101, 2, 'centrum-fyzioterapie-praha/o-nas/kvalita-sluzeb-4/individualni-pristup/upravit', 'index.php?option=com_content&a_id=163&catid=72&id=163&task=article.edit&view=article', '134', 'V Centru fyzioterapie v Horních Počernicích, Praha 9 ke každému klientovi přistupujeme individuálně od diagnostiky, plánu léčby po jednotlivá sezení. ', 'případě, zachováváme, přístup, individuální, léčebného/preventivního, programu, cvičení, skupinové', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(102, 0, 'centrum-fyzioterapie-praha/o-nas/kvalita-sluzeb/snadnost-objednani', 'index.php?option=com_content&catid=69&id=159&view=article', '134', 'Na schůzku k fyzioterapeutovi Kinisi se můžete objednat emailem, využitím formulářů na stránkách, přes online objednávkový systém nebo telefonicky.', 'nebo, telefonicky, systém, objednávkový, online, případě, nezastižení, kontaktovat', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(103, 2, 'centrum-fyzioterapie-praha/o-nas/kvalita-sluzeb/snadnost-objednani/upravit', 'index.php?option=com_content&a_id=159&catid=69&id=159&task=article.edit&view=article', '134', 'Na schůzku k fyzioterapeutovi Kinisi se můžete objednat emailem, využitím formulářů na stránkách, přes online objednávkový systém nebo telefonicky.', 'nebo, telefonicky, systém, objednávkový, online, případě, nezastižení, kontaktovat', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(104, 0, 'centrum-fyzioterapie-praha/o-nas/kvalita-sluzeb-2/koznultace-a-podpora', 'index.php?option=com_content&catid=70&id=158&view=article', '134', 'V centru fyzioterapie jsme jako zkušení fyzioterapeuté jsme klientovi pro případ potřeby konzulatce stavu a jednotlivých cvičení neustále k dispozici. ', 'nás, můžete, obrátit, během, léčebného/preventivního, budete, potřebovat, kdykoli', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(105, 2, 'centrum-fyzioterapie-praha/o-nas/kvalita-sluzeb-2/koznultace-a-podpora/upravit', 'index.php?option=com_content&a_id=158&catid=70&id=158&task=article.edit&view=article', '134', 'V centru fyzioterapie jsme jako zkušení fyzioterapeuté jsme klientovi pro případ potřeby konzulatce stavu a jednotlivých cvičení neustále k dispozici. ', 'nás, můžete, obrátit, během, léčebného/preventivního, budete, potřebovat, kdykoli', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(106, 0, 'centrum-fyzioterapie-praha/o-nas/fyzioterapeuti-praha-horni-pocernice', 'index.php?option=com_content&catid=9&id=155&view=article', '134', 'V novém centru fyzioterapie napomáháme svým klientům zbavit se akutních i chronických obtíží pohybového systému s využitím aktuálních vědeckých poznatků.', 'zbavit, kinisi, vám, centrum, fyzioterapie, zkušení, terapeuti, bolesti', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(107, 4, 'centrum-fyzioterapie-praha/o-nas/fyzioterapeuti-praha-horni-pocernice/upravit', 'index.php?option=com_content&a_id=155&catid=9&id=0&task=article.edit&view=article', '134', 'V novém centru fyzioterapie napomáháme svým klientům zbavit se akutních i chronických obtíží pohybového systému s využitím aktuálních vědeckých poznatků.', 'zbavit, kinisi, vám, centrum, fyzioterapie, zkušení, terapeuti, bolesti', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(108, 0, 'fyzioterapie-praha-kontakt/website-administrators/fyzioterapeuticke-centrum-kinisi/vcard', 'index.php?option=com_contact&format=vcf&id=1&view=contact', '142', '\'Website Administrators\' contact category description. Ut sapien enim, rhoncus sit amet fermentum at, sagittis ac massa. Fusce quis odio sit amet ipsum gravida faucibus vel et turpis. Aliquam a dui pretium elit feugiat interdum. Suspendisse tortor', 'amet, sit, sagittis, quis, ipsum, aliquam, integer, dictum', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 0, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(109, 6, 'sluzby-a-programy/fyzioterapie-dospelych/fyzioterapeuticke-vysetreni-dospelych/upravit', 'index.php?option=com_content&a_id=192&catid=84&id=192&task=article.edit&view=article', '656', 'Používané metody a terapeutické přístupy ve fyzioterapii dospělých v centru fyzioterapie Praha 9', 'výborný fyzioterapeut Praha, fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(110, 11, 'sluzby-a-programy/fyzioterapie-dospelych/upravit', 'index.php?option=com_content&a_id=227&catid=83&id=227&task=article.edit&view=article', '681', 'V pražském centru Kinisi vybíráme postup léčby ze široké škály metod a terapeutických prostředků individuálně podle potřeby každého klienta.', 'výborný fyzioterapeut Praha, soukromý fyzioterapeut, typ na fyzioterapeuta Praha', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(111, 2, 'DNS-podle-prof-pavla-kolare-dns/metody-a-lecebne-pristupy/DNS/upravit', 'index.php?option=com_content&a_id=215&catid=101&id=215&task=article.edit&view=article', '689', 'V pražském centru fyzioterapie Kinisi využíváme koncept DNS podle Prof. Koláře (DNS) - přístup založený na vývojové kineziologii.', 'svalů, břišních, zapojení, postavení, dns, terapie, symetrii, také', '', '', '', '', NULL, '', '', '0000-00-00', 0, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(112, 0, 'cenik-sluzeb/fyzioterapie-dospelych/rss', 'index.php?option=com_content&format=feed&id=35&layout=theme3447:category&type=rss&view=category', '639', '', '', '', '', '', '', NULL, '', '', '0000-00-00', 35, NULL, 1, 1, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(113, 0, 'cenik-sluzeb/fyzioterapie-dospelych/atom', 'index.php?option=com_content&format=feed&id=35&layout=theme3447:category&type=atom&view=category', '639', '', '', '', '', '', '', NULL, '', '', '0000-00-00', 35, NULL, 1, 1, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(114, 0, 'cenik-sluzeb/fyzioterapie-dospelych/fyzioterapeuticke-vysetreni-terapie', 'index.php?option=com_content&catid=35&id=184&view=article', '639', '800Kč\r\n\r\n\r\n	50 min.\r\n	Komplexní fyzioterapeutické vyšetření a terapie zahrnuje vstupní vyšetření, diagnostiku pohybového systému a následnou terapii\r\n\r\n\r\n\r\n	Objednat online\r\n	nebo\r\n	Poslat dotaz', 'vyšetření, následnou, pohybového, systému, terapii\r\n\r\n\r\n\r\n	objednat, dotaz, online\r\n	nebo\r\n	poslat, diagnostiku', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(115, 0, 'cenik-sluzeb/fyzioterapie-dospelych/fyzioterapie-50-minut', 'index.php?option=com_content&catid=35&id=182&view=article', '639', 'VVVCeny služeb Fyzioterapeutické centrum Praha 9, Horní Počernice, špičkoví fyzioterapeuti, fyzioterapie pro dospělé a děti, péče o sportovce, funkční trénink', 'obtíži, odstranění, pohybového, systému\r\n\r\n\r\n\r\n	objednat, dotaz, online\r\n	nebo\r\n	poslat, cílem, techniky', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(116, 0, 'cenik-sluzeb/fyzioterapie-dospelych/fyzioterapie-30-minut', 'index.php?option=com_content&catid=35&id=76&view=article', '639', '400Kč\r\n\r\n\r\n	30 min.\r\n	Fyzioterapeut využívá různé metody a techniky s cílem odstranění obtíži pohybového systému\r\n\r\n\r\n\r\n	Objednat online\r\n	nebo\r\n	Poslat dotaz', 'obtíži, odstranění, pohybového, systému\r\n\r\n\r\n\r\n	objednat, dotaz, online\r\n	nebo\r\n	poslat, cílem, techniky', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(117, 0, 'cenik-sluzeb/fyzioterapie-dospelych/balicek', 'index.php?option=com_content&catid=35&id=180&view=article', '639', '800Kč\r\n\r\n\r\n	50 min.\r\n	Cvičení a fyzioterapie v těhotenství\r\n\r\n\r\n\r\n	Objednat online\r\n	nebo\r\n	Poslat dotaz', 'online\r\n	nebo\r\n	poslat, dotaz, těhotenství\r\n\r\n\r\n\r\n	objednat, fyzioterapie, min, \r\n	cvičení, 800kč\r\n\r\n\r\n	50', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(118, 0, 'cenik-sluzeb/fyzioterapie-dospelych/fyzioterapie-dospelych', 'index.php?option=com_content&catid=35&id=75&view=article', '639', '800Kč\r\n\r\n\r\n	50 min.\r\n	Cvičení a fyzioterapie po porodu\r\n\r\n\r\n\r\n	Objednat online\r\n	nebo\r\n	Poslat dotaz', 'porodu\r\n\r\n\r\n\r\n	objednat, online\r\n	nebo\r\n	poslat, dotaz, fyzioterapie, min, \r\n	cvičení, 800kč\r\n\r\n\r\n	50', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(119, 0, 'cenik-sluzeb/fyzioterapie-dospelych/elektroterapie-ultrazvuk', 'index.php?option=com_content&catid=35&id=181&view=article', '639', '250Kč\r\n\r\n\r\n	20 min.\r\n	Léčba pomocí terapeutických proudů a ultrazvukového vlnění\r\n\r\n\r\n	Objednat online\r\n	nebo\r\n	Poslat dotaz', 'ultrazvukového, vlnění\r\n\r\n\r\n	objednat, online\r\n	nebo\r\n	poslat, dotaz, proudů, terapeutických, min, \r\n	léčba', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(120, 0, 'cenik-sluzeb/fyzioterapie-dospelych/kineziotaping', 'index.php?option=com_content&catid=35&id=183&view=article', '639', '400Kč\r\n\r\n\r\n	30 min.\r\n	Aplikace terapeutické elastické pásky na tělo pro uvolnění nebo stabilizaci kloubů a svalů\r\n\r\n\r\n\r\n	Objednat online\r\n	nebo\r\n	Poslat dotaz', 'stabilizaci, nebo, uvolnění, kloubů, svalů\r\n\r\n\r\n\r\n	objednat, dotaz, online\r\n	nebo\r\n	poslat, pro', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(121, 2, 'ceny-fyzioterapie-dospelych/stranky/cenik-sluzeb/fyzioterapie-dospelych/fyzioterapeuticke-vysetreni-terapie/upravit', 'index.php?option=com_content&a_id=184&catid=35&id=184&task=article.edit&view=article', '639', '800Kč	50 min.	Komplexní fyzioterapeutické vyšetření a terapie zahrnuje vstupní vyšetření, diagnostiku pohybového systému a následnou terapii	Objednat online	nebo	Poslat dotaz', 'vyšetření, následnou, pohybového, systému, terapii	objednat, dotaz, online	nebo	poslat, diagnostiku', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(122, 2, 'ceny-fyzioterapie-dospelych/stranky/cenik-sluzeb/fyzioterapie-dospelych/fyzioterapie-50/upravit', 'index.php?option=com_content&a_id=182&catid=35&id=182&task=article.edit&view=article', '639', 'VVVCeny služeb Fyzioterapeutické centrum Praha 9, Horní Počernice, špičkoví fyzioterapeuti, fyzioterapie pro dospělé a děti, péče o sportovce, funkční trénink', 'obtíži, odstranění, pohybového, systému	objednat, dotaz, online	nebo	poslat, cílem, techniky', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(123, 0, 'cenik-sluzeb/fyzioterapie-dospelych/fyzioterapie-30/upravit', 'index.php?option=com_content&a_id=76&catid=35&id=76&task=article.edit&view=article', '639', '400Kč	30 min.	Fyzioterapeut využívá různé metody a techniky s cílem odstranění obtíži pohybového systému	Objednat online	nebo	Poslat dotaz', 'obtíži, odstranění, pohybového, systému	objednat, dotaz, online	nebo	poslat, cílem, techniky', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(124, 0, 'ceny-fyzioterapie-dospelych/stranky/cenik-sluzeb/fyzioterapie-dospelych/third-package-2/upravit', 'index.php?option=com_content&a_id=180&catid=35&id=180&task=article.edit&view=article', '639', '800Kč	50 min.	Cvičení a fyzioterapie v těhotenství	Objednat online	nebo	Poslat dotaz', 'online	nebo	poslat, dotaz, těhotenství	objednat, fyzioterapie, min, 	cvičení, 800kč	50', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(125, 0, 'ceny-fyzioterapie-dospelych/stranky/cenik-sluzeb/fyzioterapie-dospelych/fyzioterapie-dospelych/upravit', 'index.php?option=com_content&a_id=75&catid=35&id=75&task=article.edit&view=article', '639', '800Kč	50 min.	Cvičení a fyzioterapie po porodu	Objednat online	nebo	Poslat dotaz', 'porodu	objednat, online	nebo	poslat, dotaz, fyzioterapie, min, 	cvičení, 800kč	50', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(126, 0, 'cenik-sluzeb/fyzioterapie-dospelych/elektroterapie-ultrazvuk/upravit', 'index.php?option=com_content&a_id=181&catid=35&id=181&task=article.edit&view=article', '639', '250Kč	20 min.	Léčba pomocí terapeutických proudů a ultrazvukového vlnění	Objednat online	nebo	Poslat dotaz', 'ultrazvukového, vlnění	objednat, online	nebo	poslat, dotaz, proudů, terapeutických, min, 	léčba', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(127, 0, 'ceny-fyzioterapie-dospelych/stranky/cenik-sluzeb/fyzioterapie-dospelych/kineziotaping/upravit', 'index.php?option=com_content&a_id=183&catid=35&id=183&task=article.edit&view=article', '639', '400Kč	30 min.	Aplikace terapeutické elastické pásky na tělo pro uvolnění nebo stabilizaci kloubů a svalů	Objednat online	nebo	Poslat dotaz', 'stabilizaci, nebo, uvolnění, kloubů, svalů	objednat, dotaz, online	nebo	poslat, pro', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(128, 0, 'ceny-fyzioterapie-dospelych', 'index.php?option=com_content&view=categories', '639', '', '', '', '', '', '', NULL, '', '', '2017-12-12', 90, NULL, 1, 1, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(129, 14, 'sluzby-a-programy/fyzioterapie-dospelych/indikace/upravit', 'index.php?option=com_content&a_id=193&catid=84&id=193&task=article.edit&view=article', '657', 'Používané metody a terapeutické přístupy ve fyzioterapii dospělých v centru', '111', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(130, 10, 'sluzby-a-programy/fyzioterapie-dospelych/metody-a-terapeuticke-pristupy-ve-fyzioterapii-dospelych/upravit', 'index.php?option=com_content&a_id=194&catid=84&id=194&task=article.edit&view=article', '658', 'Používané metody a terapeutické přístupy ve fyzioterapii dospělých v centru fyzioterapie Kinisi na Praze 9', 'integrace, stimulace, primitivních, reflexů,synergická, reflexní, 	senzomotorická, dns', '', '', '', '', NULL, '', '', '2017-12-12', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(131, 0, 'ochrana-soukromi/podminky-uziti/rss', 'index.php?option=com_content&format=feed&id=10&layout=theme3447:category&type=rss&view=category', '176', '', '', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 35, NULL, 1, 0, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(132, 0, 'ochrana-soukromi/podminky-uziti/atom', 'index.php?option=com_content&format=feed&id=10&layout=theme3447:category&type=atom&view=category', '176', '', '', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 35, NULL, 1, 0, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(133, 5, 'ochrana-soukromi/podminky-uziti/podminky-uziti/upravit', 'index.php?option=com_content&a_id=6&catid=10&id=6&task=article.edit&view=article', '176', 'Autorská práva - Vlastníkem a provozovatelem internetových stránek kinisi.cz je společnost Kinisi, s.r.o. Centrum fyzioterapie, ', 'autorská práva, fyzioterapie, fyzioterapie Praha 9', '', '', NULL, '', NULL, NULL, '', '2017-12-12', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(134, 2, 'config', 'index.php?option=com_config', NULL, '', '', '', '', '', '', NULL, '', '', '2017-12-12', 95, NULL, 1, 0, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(135, 0, 'moduly', 'index.php?option=com_modules&view=modules', NULL, '', '', '', '', '', '', NULL, '', '', '2017-12-12', 95, NULL, 1, 1, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(136, 0, 'cenik-sluzeb/detska-fyzioterapie/rss', 'index.php?option=com_content&format=feed&id=77&layout=theme3447:category&type=rss&view=category', '640', '', '', '', '', '', '', NULL, '', '', '0000-00-00', 35, NULL, 1, 1, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(137, 0, 'ceny-detska-fyzioterapie/stranky/cenik-sluzeb/detska-fyzioterapie/atom', 'index.php?option=com_content&format=feed&id=77&layout=theme3447:category&type=atom&view=category', '640', '', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 35, NULL, 1, 0, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(138, 0, 'cenik-sluzeb/detska-fyzioterapie/komplexni-vysetreni-a-terapie', 'index.php?option=com_content&catid=77&id=187&view=article', '640', '800Kč\r\n\r\n\r\n	50 min.\r\n	Komplexní fyzioterapeutické vyšetření a terapie zahrnuje vstupní vyšetření, diagnostiku pohybového systému dítěte a následnou terapii\r\n\r\n\r\n\r\n	Objednat online\r\n	nebo\r\n	Poslat dotaz', 'vyšetření, následnou, systému, dítěte, terapii\r\n\r\n\r\n\r\n	objednat, dotaz, online\r\n	nebo\r\n	poslat, pohybového', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(139, 0, 'cenik-sluzeb/detska-fyzioterapie/fyzioterapie-50-min', 'index.php?option=com_content&catid=77&id=186&view=article', '640', '800Kč\r\n\r\n\r\n	50 min.\r\n	Zahrnuje cvičení a terapií dítěte, které již absolvovalo vstupní vyšetření\r\n\r\n\r\n	Objednat online\r\n	nebo\r\n	Poslat dotaz', 'vstupní, absolvovalo, vyšetření\r\n\r\n\r\n	objednat, online\r\n	nebo\r\n	poslat, dotaz, již, které, \r\n	zahrnuje', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(140, 0, 'cenik-sluzeb/detska-fyzioterapie/fyzioterapie-30-min', 'index.php?option=com_content&catid=77&id=185&view=article', '640', '400Kč\r\n\r\n\r\n	30 min.\r\n	Zahrnuje cvičení a terapií dítěte, které již absolvovalo vstupní vyšetření\r\n\r\n\r\n\r\n	Objednat online\r\n	nebo\r\n	Poslat dotaz', 'vstupní, absolvovalo, vyšetření\r\n\r\n\r\n\r\n	objednat, online\r\n	nebo\r\n	poslat, dotaz, již, které, \r\n	zahrnuje', '', '', '', '', NULL, '', '', '0000-00-00', 15, NULL, 1, 1, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(141, 0, 'tags/media/rss', 'index.php?option=com_tags&format=feed&id=12&type=rss&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(142, 0, 'tags/media/atom', 'index.php?option=com_tags&format=feed&id=12&type=atom&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(143, 0, 'tags', 'index.php?option=com_tags', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-12', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(144, 0, 'kinisi-fyzioterapie-hp/uncategorised/forum-informace', 'index.php?option=com_content&catid=2&id=191&view=article', NULL, 'Pro položení dotazu nebo založení téma k diskusi se prosím přihlašte a po klinknutí na položku menu&nbsp;&quot;Vložit nové téma, dotaz&quot; viditelnou pro registrované uživatele, zadejte svůj dotaz/téma.\r\n\r\nDotazy vložené do fóra jsou zveřejňovány', 'pro, uživatele, otázky, téma, kinisi, dotazu, nebo, stejnými', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 20, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
