
DROP TABLE IF EXISTS `bc73q_roksprocket_items`;
CREATE TABLE `bc73q_roksprocket_items` (
  `id` int(11) NOT NULL,
  `module_id` varchar(45) NOT NULL,
  `provider` varchar(45) NOT NULL,
  `provider_id` varchar(45) NOT NULL,
  `order` int(10) UNSIGNED NOT NULL,
  `params` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `bc73q_roksprocket_items` VALUES(37, '287', 'joomla', '223', 0, '{\"grids_item_title\":\"-default-\",\"grids_item_description\":\"-default-\",\"grids_item_image\":\"-default-\",\"grids_item_link\":\"-default-\",\"strips_item_title\":\"-default-\",\"tabs_item_title\":\"-default-\",\"tables_item_title\":\"-default-\",\"mosaic_item_title\":\"-default-\",\"lists_item_title\":\"-default-\",\"mosaic_item_description\":\"-default-\",\"tabs_item_icon\":\"-default-\",\"tables_item_description\":\"-default-\",\"quotes_item_description\":\"-default-\",\"mosaic_item_image\":\"-default-\",\"lists_item_image\":\"-default-\",\"quotes_item_image\":\"-default-\",\"tabs_item_link\":\"-default-\",\"strips_item_image\":\"-default-\",\"tables_item_image\":\"-default-\",\"tabs_item_description\":\"-default-\",\"mosaic_item_link\":\"-default-\",\"quotes_item_author\":\"-none-\",\"lists_item_link\":\"-default-\",\"tables_item_class\":\"-none-\",\"strips_item_link\":\"-default-\",\"mosaic_item_tags\":\"-article-\",\"tables_item_price\":\"-none-\",\"features_item_title\":\"-default-\",\"quotes_item_subtext\":\"-none-\",\"sliders_item_title\":\"-default-\",\"features_item_description\":\"-default-\",\"sliders_item_description\":\"-default-\",\"strips_item_description\":\"-default-\",\"tables_item_feature_1\":\"-none-\",\"headlines_item_image\":\"-default-\",\"quotes_item_link\":\"-default-\",\"lists_item_description\":\"-default-\",\"tables_item_feature_2\":\"-none-\",\"quotes_item_direction\":\"-bottomleft-\",\"headlines_item_link\":\"-default-\",\"features_item_image\":\"-default-\",\"sliders_item_image\":\"-default-\",\"tables_item_feature_3\":\"-none-\",\"headlines_item_description\":\"-default-\",\"sliders_item_link\":\"-default-\",\"features_item_link\":\"-default-\",\"tables_item_feature_4\":\"-none-\",\"tables_item_link\":\"-default-\",\"tables_item_link_text\":\"Buy Now\"}');
INSERT INTO `bc73q_roksprocket_items` VALUES(38, '287', 'joomla', '224', 1, '{\"grids_item_title\":\"-default-\",\"grids_item_description\":\"-default-\",\"grids_item_image\":\"-default-\",\"grids_item_link\":\"-default-\",\"strips_item_title\":\"-default-\",\"tabs_item_title\":\"-default-\",\"tables_item_title\":\"-default-\",\"mosaic_item_title\":\"-default-\",\"lists_item_title\":\"-default-\",\"mosaic_item_description\":\"-default-\",\"tabs_item_icon\":\"-default-\",\"tables_item_description\":\"-default-\",\"quotes_item_description\":\"-default-\",\"mosaic_item_image\":\"-default-\",\"lists_item_image\":\"-default-\",\"quotes_item_image\":\"-default-\",\"tabs_item_link\":\"-default-\",\"strips_item_image\":\"-default-\",\"tables_item_image\":\"-default-\",\"tabs_item_description\":\"-default-\",\"mosaic_item_link\":\"-default-\",\"quotes_item_author\":\"-none-\",\"lists_item_link\":\"-default-\",\"tables_item_class\":\"-none-\",\"strips_item_link\":\"-default-\",\"mosaic_item_tags\":\"-article-\",\"tables_item_price\":\"-none-\",\"features_item_title\":\"-default-\",\"quotes_item_subtext\":\"-none-\",\"sliders_item_title\":\"-default-\",\"features_item_description\":\"-default-\",\"sliders_item_description\":\"-default-\",\"strips_item_description\":\"-default-\",\"tables_item_feature_1\":\"-none-\",\"headlines_item_image\":\"-default-\",\"quotes_item_link\":\"-default-\",\"lists_item_description\":\"-default-\",\"tables_item_feature_2\":\"-none-\",\"quotes_item_direction\":\"-bottomleft-\",\"headlines_item_link\":\"-default-\",\"features_item_image\":\"-default-\",\"sliders_item_image\":\"-default-\",\"tables_item_feature_3\":\"-none-\",\"headlines_item_description\":\"-default-\",\"sliders_item_link\":\"-default-\",\"features_item_link\":\"-default-\",\"tables_item_feature_4\":\"-none-\",\"tables_item_link\":\"-default-\",\"tables_item_link_text\":\"Buy Now\"}');
INSERT INTO `bc73q_roksprocket_items` VALUES(39, '287', 'joomla', '225', 2, '{\"grids_item_title\":\"-default-\",\"grids_item_description\":\"-default-\",\"grids_item_image\":\"-default-\",\"grids_item_link\":\"-default-\",\"strips_item_title\":\"-default-\",\"tabs_item_title\":\"-default-\",\"tables_item_title\":\"-default-\",\"mosaic_item_title\":\"-default-\",\"lists_item_title\":\"-default-\",\"mosaic_item_description\":\"-default-\",\"tabs_item_icon\":\"-default-\",\"tables_item_description\":\"-default-\",\"quotes_item_description\":\"-default-\",\"mosaic_item_image\":\"-default-\",\"lists_item_image\":\"-default-\",\"quotes_item_image\":\"-default-\",\"tabs_item_link\":\"-default-\",\"strips_item_image\":\"-default-\",\"tables_item_image\":\"-default-\",\"tabs_item_description\":\"-default-\",\"mosaic_item_link\":\"-default-\",\"quotes_item_author\":\"-none-\",\"lists_item_link\":\"-default-\",\"tables_item_class\":\"-none-\",\"strips_item_link\":\"-default-\",\"mosaic_item_tags\":\"-article-\",\"tables_item_price\":\"-none-\",\"features_item_title\":\"-default-\",\"quotes_item_subtext\":\"-none-\",\"sliders_item_title\":\"-default-\",\"features_item_description\":\"-default-\",\"sliders_item_description\":\"-default-\",\"strips_item_description\":\"-default-\",\"tables_item_feature_1\":\"-none-\",\"headlines_item_image\":\"-default-\",\"quotes_item_link\":\"-default-\",\"lists_item_description\":\"-default-\",\"tables_item_feature_2\":\"-none-\",\"quotes_item_direction\":\"-bottomleft-\",\"headlines_item_link\":\"-default-\",\"features_item_image\":\"-default-\",\"sliders_item_image\":\"-default-\",\"tables_item_feature_3\":\"-none-\",\"headlines_item_description\":\"-default-\",\"sliders_item_link\":\"-default-\",\"features_item_link\":\"-default-\",\"tables_item_feature_4\":\"-none-\",\"tables_item_link\":\"-default-\",\"tables_item_link_text\":\"Buy Now\"}');
INSERT INTO `bc73q_roksprocket_items` VALUES(40, '287', 'joomla', '226', 3, '{\"grids_item_title\":\"-default-\",\"grids_item_description\":\"-default-\",\"grids_item_image\":\"-default-\",\"grids_item_link\":\"-default-\",\"strips_item_title\":\"-default-\",\"tabs_item_title\":\"-default-\",\"tables_item_title\":\"-default-\",\"mosaic_item_title\":\"-default-\",\"lists_item_title\":\"-default-\",\"mosaic_item_description\":\"-default-\",\"tabs_item_icon\":\"-default-\",\"tables_item_description\":\"-default-\",\"quotes_item_description\":\"-default-\",\"mosaic_item_image\":\"-default-\",\"lists_item_image\":\"-default-\",\"quotes_item_image\":\"-default-\",\"tabs_item_link\":\"-default-\",\"strips_item_image\":\"-default-\",\"tables_item_image\":\"-default-\",\"tabs_item_description\":\"-default-\",\"mosaic_item_link\":\"-default-\",\"quotes_item_author\":\"-none-\",\"lists_item_link\":\"-default-\",\"tables_item_class\":\"-none-\",\"strips_item_link\":\"-default-\",\"mosaic_item_tags\":\"-article-\",\"tables_item_price\":\"-none-\",\"features_item_title\":\"-default-\",\"quotes_item_subtext\":\"-none-\",\"sliders_item_title\":\"-default-\",\"features_item_description\":\"-default-\",\"sliders_item_description\":\"-default-\",\"strips_item_description\":\"-default-\",\"tables_item_feature_1\":\"-none-\",\"headlines_item_image\":\"-default-\",\"quotes_item_link\":\"-default-\",\"lists_item_description\":\"-default-\",\"tables_item_feature_2\":\"-none-\",\"quotes_item_direction\":\"-bottomleft-\",\"headlines_item_link\":\"-default-\",\"features_item_image\":\"-default-\",\"sliders_item_image\":\"-default-\",\"tables_item_feature_3\":\"-none-\",\"headlines_item_description\":\"-default-\",\"sliders_item_link\":\"-default-\",\"features_item_link\":\"-default-\",\"tables_item_feature_4\":\"-none-\",\"tables_item_link\":\"-default-\",\"tables_item_link_text\":\"Buy Now\"}');
