
DROP TABLE IF EXISTS `bc73q_gsd`;
CREATE TABLE `bc73q_gsd` (
  `id` int(10) UNSIGNED NOT NULL,
  `params` text,
  `thing` int(11) NOT NULL DEFAULT '0' COMMENT 'The primary key of the referenced item',
  `plugin` varchar(50) NOT NULL DEFAULT '0' COMMENT 'The plugin name of the referenced item',
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ordering` int(11) NOT NULL DEFAULT '0',
  `state` tinyint(3) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `bc73q_gsd` VALUES(1, '{\"contenttype\":\"article\",\"article\":{\"headline\":\"\",\"description\":\"\",\"author\":{\"option\":\"0\",\"user\":\"0\",\"custom\":\"\"},\"image\":{\"option\":\"1\",\"file\":\"\",\"url\":\"\"}},\"event\":{\"type\":\"Event\",\"description\":\"\",\"image\":{\"option\":\"1\",\"file\":\"\",\"url\":\"\"},\"startDate\":\"2017-12-07\",\"startTime\":\"00:00\",\"endDate\":\"2017-12-07\",\"endTime\":\"00:00\",\"status\":\"http:\\/\\/schema.org\\/EventScheduled\",\"locationName\":\"\",\"locationAddress\":\"\",\"homeTeam\":\"\",\"awayTeam\":\"\",\"performerType\":\"Person\",\"performerName\":\"\",\"offerAvailability\":\"http:\\/\\/schema.org\\/InStock\",\"offerStartDate\":\"2017-12-07\",\"offerStartTime\":\"00:00\",\"offerPrice\":\"0\",\"offerCurrency\":\"EUR\",\"offerInventoryLevel\":\"0\"},\"product\":{\"description\":\"\",\"image\":{\"option\":\"1\",\"file\":\"\",\"url\":\"\"},\"rating\":{\"option\":\"1\",\"ratingValue\":\"5\",\"reviewCount\":\"1\"},\"sku\":\"\",\"brandName\":\"\",\"offerPrice\":\"\",\"currency\":\"EUR\",\"offerItemCondition\":\"http:\\/\\/schema.org\\/NewCondition\",\"offerAvailability\":\"http:\\/\\/schema.org\\/InStock\"},\"recipe\":{\"headline\":\"\",\"description\":\"\",\"author\":{\"option\":\"0\",\"user\":\"0\",\"custom\":\"\"},\"image\":{\"option\":\"1\",\"file\":\"\",\"url\":\"\"},\"rating\":{\"option\":\"1\",\"ratingValue\":\"5\",\"reviewCount\":\"1\"},\"prepTime\":\"\",\"cookTime\":\"\",\"totalTime\":\"\",\"calories\":\"\",\"yield\":\"\",\"ingredient\":\"\",\"instructions\":\"\"},\"course\":{\"headline\":\"\",\"description\":\"\",\"image\":{\"option\":\"1\",\"file\":\"\",\"url\":\"\"},\"rating\":{\"option\":\"1\",\"ratingValue\":\"5\",\"reviewCount\":\"1\"}},\"review\":{\"headline\":\"\",\"description\":\"\",\"author\":{\"option\":\"0\",\"user\":\"0\",\"custom\":\"\"},\"image\":{\"option\":\"1\",\"file\":\"\",\"url\":\"\"},\"rating\":{\"option\":\"1\",\"ratingValue\":\"5\"},\"itemReviewedType\":\"Thing\",\"address\":\"\",\"priceRange\":\"\",\"telephone\":\"\"},\"factcheck\":{\"headline\":\"\",\"claimDatePublished\":\"2017-12-07\",\"claimURL\":\"\",\"claimAuthorName\":\"\",\"claimAuthorType\":\"Organization\",\"factcheckRating\":\"-1\",\"multiple\":\"0\",\"anchorName\":\"\"},\"note\":\"\",\"colorgroup\":\"none\"}', 231, 'content', '2017-12-07 15:19:13', 0, 1);
