
DROP TABLE IF EXISTS `bc73q_sefurls`;
CREATE TABLE `bc73q_sefurls` (
  `id` int(11) NOT NULL,
  `cpt` int(11) NOT NULL DEFAULT '0',
  `sefurl` varchar(255) NOT NULL,
  `origurl` varchar(255) NOT NULL,
  `Itemid` varchar(20) DEFAULT NULL,
  `metadesc` varchar(255) DEFAULT '',
  `metakey` varchar(255) DEFAULT '',
  `metatitle` varchar(255) DEFAULT '',
  `metalang` varchar(30) DEFAULT '',
  `metarobots` varchar(30) DEFAULT '',
  `metagoogle` varchar(30) DEFAULT '',
  `metacustom` text,
  `metaauthor` varchar(30) DEFAULT '',
  `canonicallink` varchar(255) DEFAULT '',
  `dateadd` date NOT NULL DEFAULT '0000-00-00',
  `priority` int(11) NOT NULL DEFAULT '0',
  `trace` text,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `locked` tinyint(1) NOT NULL DEFAULT '0',
  `sef` tinyint(1) NOT NULL DEFAULT '1',
  `sm_indexed` tinyint(1) NOT NULL DEFAULT '0',
  `sm_date` date NOT NULL DEFAULT '0000-00-00',
  `sm_frequency` varchar(20) NOT NULL DEFAULT 'weekly',
  `sm_priority` varchar(10) NOT NULL DEFAULT '0.5',
  `flag` tinyint(1) NOT NULL DEFAULT '0',
  `host` varchar(255) NOT NULL DEFAULT '',
  `showsitename` int(1) NOT NULL DEFAULT '3'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `bc73q_sefurls` VALUES(1, 0, 'nas-tym/o-nas/our-advantages/rss', 'index.php?option=com_content&format=feed&id=67&layout=theme3447:category&type=rss&view=category', '701', '', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 35, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(2, 0, 'nas-tym/o-nas/our-advantages/atom', 'index.php?option=com_content&format=feed&id=67&layout=theme3447:category&type=atom&view=category', '701', '', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 35, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(3, 0, 'ochrana-soukromi/podminky-uziti', 'index.php?option=com_content&id=10&layout=theme3447:category&view=category', '176', '', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 35, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(4, 0, 'centrum-fyzioterapie-praha/o-nas', 'index.php?option=com_content&id=9&layout=theme3447:category&view=category', '134', '', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 35, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(5, 2, 'nas-tym/o-nas/our-advantages', 'index.php?option=com_content&id=67&layout=theme3447:category&view=category', '701', '', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 35, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(6, 84, '', 'index.php?option=com_content&id=8&layout=theme3447:category&view=category', '101', '', '', '', '', '', '', NULL, '', '', '0000-00-00', 90, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(7, 0, 'nas-tym/uncategorised/kinisi-fyzioterapie-logo', 'index.php?option=com_content&catid=2&id=144&view=article', '701', 'Centrum fyzioterapie Kinisi, Praha 9 - Horní Počernice spojuje profesionální přístup zkušených fyzioterapeutů se špičkovým moderním vybavením.', 'příjemném, prostředí, pracujeme, klienty, svými, našeho, centra, počernicích', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(8, 0, 'nas-tym/hp-reference/reference-technology-florbal-mlada-boleslav', 'index.php?option=com_content&catid=66&id=151&view=article', '701', 'Reference na Mgr. Vojtoviče z fyzioterapeutického centra Kinisi v Praze 9, Horních Počernicích - Technology Florbal MB', 'hlavní, mgr, fyzioterapie, sezóny, kinisi, vojtovič, podílí, zdravotně-kondiční', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(9, 0, 'nas-tym/hp-reference/acema-sparta-praha-florbal', 'index.php?option=com_content&catid=66&id=152&view=article', '701', 'Reference na Bc. M. Hrickovou z fyzioterapeutického centra Kinisi v Praze 9, Horní Počernice - ACEMA Sparta Praha Florbal', 'business, key, members, operation, significant, aspect, organization, high', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(10, 0, 'nas-tym/hp-reference/reference-vanecek', 'index.php?option=com_content&catid=66&id=153&view=article', '701', 'Fyzioterapeutické centrum Kinisi v Horních Počernicích získává stále více pozitivních hodnocení od svých klientů.', 'business, key, members, operation, significant, aspect, organization, high', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(11, 0, 'reference/uncategorised/reference-fyzioterapie-kinisi-praha', 'index.php?option=com_content&catid=2&id=177&view=article', '137', 'Reference na Centrum fyzioterapie v Horních Počernicích, Praha 9', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(12, 0, 'nas-tym/stranky/tym-fyzioterapie-kinisi/fyzioterapeutka-hrickova', 'index.php?option=com_content&catid=26&id=44&view=article', '701', 'Fyzioterapeutka Kinisi, Praha 9 - Horní Počernice vedle sportovců pracuje s dospělými, dětmi od 2 let a neurologickými pacienty. ', 'studia, kde, vedené, komplexně, pacienty, zakládá, neurologickými, sportovců', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(13, 2, 'nas-tym/stranky/tym-fyzioterapie-kinisi/mgr-martin-vojtovic', 'index.php?option=com_content&catid=26&id=46&view=article', '701', 'Výborný fyzioterapeut Kinisi, Praha 9 - Horní Počernice se specializuje zejména na sportovní fyzioterapii a funkční trénink.', 'Fyzioterapeut Mgr. Martin Vojtovič, Fyzioterapeut Praha 9, Fyzioterapeut Praha 8, Fyzioterapeut Horní Počernice', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(14, 2, 'nas-tym/stranky/tym-fyzioterapie-kinisi/fyzioterapeutka-augustinova', 'index.php?option=com_content&catid=26&id=45&view=article', '701', 'Úspěšná fyzioterapeutka Kinisi, Praha 9 - Horní Počernice ', 'terapii, své, univerzity, její, fyzioterapie, roce, léčbě, vztahy', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(15, 0, 'zakladni-informace/sluzby-a-programy/fyzioterapie-dospelych-zakladni-info', 'index.php?option=com_content&catid=83&id=227&view=article', '681', 'V pražském centru Kinisi vybíráme postup léčby ze široké škály metod a terapeutických prostředků individuálně podle potřeby každého klienta. ', 'pohybů, tak, aby, normalizace, obnovení, cílem, nedocházelo, přetížení', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(16, 2, 'vysetreni/sluzby-a-programy/fyzioterapie-dospelych/fyzioterapeuticke-vysetreni-dospelych', 'index.php?option=com_content&catid=84&id=192&view=article', '656', 'Používané metody a terapeutické přístupy ve fyzioterapii dospělých v centru ', 'vyšetření, pohybové, fyzioterapeutické, soustavy, základními, jsou, anamnézy, stanovení', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(17, 0, 'indikace/sluzby-a-programy/fyzioterapie-dospelych/indikace', 'index.php?option=com_content&catid=84&id=193&view=article', '657', 'Používané metody a terapeutické přístupy ve fyzioterapii dospělých v centru ', '\r\n\r\n&nbsp, bolesti, syndrom, kloubů, \r\n\r\n\r\n\r\n&nbsp, stavy, vazů, ramene', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(18, 0, 'metody-a-terapeuticke-pristupy/sluzby-a-programy/fyzioterapie-dospelych/metody-a-terapeuticke-pristupy-ve-fyzioterapii-dospelych', 'index.php?option=com_content&catid=84&id=194&view=article', '658', 'Používané metody a terapeutické přístupy ve fyzioterapii dospělých v centru fyzioterapie Kinisi na Praze 9', '\r\n	integrace, stimulace, primitivních, reflexů\r\n	synergická, reflexní, \r\n	senzomotorická, dns, podle', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(19, 0, 'zakladni-informace/sluzby-a-programy/detska-fyzioterapie-zakladni-informace', 'index.php?option=com_content&catid=83&id=226&view=article', '682', 'Posláním fyzioterapeutů v pražském centru Kinisi je zachytit a ovlivnit v co nejmladším věku  odchylky ve vývoji dítěte.', 'odchylky, vývoji, dítěte, ovlivnit, zachytit, fyzioterapeutů, centru, kinisi', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(20, 0, 'vysetreni/sluzby-a-programy/detska-fyzioterapie/vysetreni-v-detske-fyzioterapii', 'index.php?option=com_content&catid=88&id=195&view=article', '664', 'Komplexní fyzioterapeutické vyšetření u dětí ve věku 5–18 let je zaměřeno na řešení akutních i chronických obtíží pohybového systému.', 'jsou, pohybového, které, dítěte, vyšetření, systému, při, věku', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(21, 0, 'indikace/sluzby-a-programy/detska-fyzioterapie/indikace-v-detske-fyzioterapii', 'index.php?option=com_content&catid=88&id=196&view=article', '665', 'Indikace v dětské fyzioterapii, které se věnujeme ve fyzioterapeutickém centru Kinisi v Praze 9', 'korekce, poruchou, jako, stavy, péče, kloubů, \r\n\r\n&nbsp, pozornosti', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(22, 0, 'metody-a-terapeuticke-pristupy/sluzby-a-programy/detska-fyzioterapie/metody-a-terapeuticke-pristupy-v-detske-fyzioterapii', 'index.php?option=com_content&catid=88&id=197&view=article', '666', 'V Kinisi využíváme mezinárodně uznávané vědecké metody, které respektují neurofyhybziologické principy lidského těla a pou.', 'dns, \r\n	senzomotorická, stimulace, koláře, pavla, podle, prof, \r\n	integrace', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(23, 0, 'zakladni-informace/sluzby-a-programy/fyzioterapie-pro-zeny-zakladni-informace', 'index.php?option=com_content&catid=83&id=225&view=article', '685', 'Zaměřujeme se na ženy toužící otěhotnět, ženy, které mají v těhotenství potíže s pohybovým aparátem nebo se chtějí udržovat v dobré fyzické kondici. ', 'také, ženy, posílit, břišní, zádové, dna, pánevního, svalů', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(24, 0, 'lecba-funkcni-sterility/sluzby-a-programy/fyzioterapie-pro-zeny/lecba-funkcni-sterility', 'index.php?option=com_content&catid=99&id=204&view=article', '672', 'V fyzioterapeutickém centru v Horních Počernicích v Praze se specializujeme se  na funkční sterilitu.', 'při, pánevního, oblasti, svalů, cvičení, ošetření, dna, napětí', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(25, 4, 'fyzioterapie-v-tehotenstvi/sluzby-a-programy/fyzioterapie-pro-zeny/fyzioterapie-v-tehotenstvi', 'index.php?option=com_content&catid=99&id=205&view=article', '673', 'Přiměřený pohyb je základem správné životosprávy v těhotenství a jeho záměrem je udržet budoucí maminky v co nejlepší fyzické a psychické kondici.', 'svaly, těhotenství, vzniku, pro, dochází, také, cvičení, systému', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(26, 0, 'fyzioterapie-po-porodu/sluzby-a-programy/fyzioterapie-pro-zeny/fyzioterapie-po-porodu', 'index.php?option=com_content&catid=99&id=206&view=article', '674', 'Po nekomplikovaném porodu žena začíná cvičit po 12-24 hodinách. Hlavním cílem cvičení je povzbudit krevní oběh a předejít tak tromboembolické nemoci. ', 'cvičení, svalů, dělohy, dle, také, pánevního, správnou, zavinování', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(27, 0, 'zakladni-informace/sluzby-a-programy/akutni-a-pooperacni-fyzioterapie-2', 'index.php?option=com_content&catid=83&id=230&view=article', '683', 'V Kinisi se zaměřujeme na  akutní bolesti pohybového systému a pooperační fyzioterapii ', 'fyzioterapie, akutní, bolesti, zachování, obnova, otoku, plného, pohybu', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(28, 0, 'akutni-fyzioterapie/sluzby-a-programy/akutni-a-pooperacni-fyzioterapie/lecba-urazu-a-akutnich-bolestivych-blokad', 'index.php?option=com_content&catid=92&id=198&view=article', '667', 'V fyzioterapeutickém centru v Horních Počernicích v Praze poskytujeme klientům akutní fyzioterapii', 'bolesti, akutní, blokády, akutních, kloubů, nebo, fyzioterapie, blokáda', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(29, 0, 'pooperacni-fyzioterapie/sluzby-a-programy/akutni-a-pooperacni-fyzioterapie/pooperacni-pece-a-lecba', 'index.php?option=com_content&catid=92&id=200&view=article', '668', 'V fyzioterapeutickém centru v Horních Počernicích v Praze poskytujeme klientům V fyzioterapeutickém centru v Horních Počernicích v Praze poskytujeme klientům předoperační léčbu a pooperační péči', 'operaci, páteře, využíváme, také, pohybu, tkání, pooperační, rozsahu', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(30, 0, 'zakladni-informace/sluzby-a-programy/funkcni-fyziotrenink-zakladni-informace', 'index.php?option=com_content&catid=83&id=229&view=article', '684', 'Naším cílem je dijít k efektivní účelné svalové aktivaci, zvýšení sportovní výkonnosti, menšímu opotřebení pohybového systému a kompenzaci stresové zátěže.', 'opotřebení, pohybového, systému, menšímu, výkonnosti, aktivaci, zvýšení, sportovní', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(31, 0, 'preventivni-programy/sluzby-a-programy/funkcni-fyziotrening/preventivni-programy-ve-funkcnim-fyziotreninku', 'index.php?option=com_content&catid=95&id=201&view=article', '669', 'Ve spolupráci s fyzioterapeutem Mgr. Martinem Vojtovičem jsme v Kinisi vypracovali speciální preventivní program pro vrcholové i amatérské sportovce.', 'program, následně, rámci, plán, pohybového, preventivní, cvičení, aby', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(32, 0, 'spravne-cviceni-a-posilovani/sluzby-a-programy/funkcni-fyziotrening/spravne-cviceni-a-posilovani-v-funkcnim-fyziotreninku', 'index.php?option=com_content&catid=95&id=202&view=article', '670', 'Předpokladem správného posilování je porozumění vlastnímu tělu,  součástí tréninku by měli být techniky  na uvědomění tělesných částí a pohybů.', 'sportu, např, tak, posilování, správného, konkrétním, zlepšit, pohybového', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(33, 0, 'metody-a-treninkove-prostredky/sluzby-a-programy/funkcni-fyziotrening/metody-a-treninkove-prostredky-funkcniho-fyziotreningu', 'index.php?option=com_content&catid=95&id=203&view=article', '671', 'Metody a tréninkové prostředky funkčního fyziotréningu', 'flowin\r\n\r\n&nbsp, aguahit\r\n\r\n&nbsp, bosu\r\n\r\n\r\n\r\n&nbsp, thera-band\r\n\r\n\r\n\r\n&nbsp, blackroll\r\n\r\n&nbsp, gymball, spine\r\n\r\n&nbsp, sliding', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(34, 0, 'zakladni-informace/sluzby-a-programy/pece-o-sportovce-zakladni-informace', 'index.php?option=com_content&catid=83&id=228&view=article', '686', 'V pražském centru v Horních Počernicích se specializujeme na sportovní fyzioterapii a péčí o sportovce. ', 'analýza, vzorů, pohybových, sportovců, bezpečný, návrat, sportovce, nejrychlejší', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(35, 0, 'komplexni-analyza-sportovce/sluzby-a-programy/pece-o-sportovce/komplexni-analyza-sportovce', 'index.php?option=com_content&catid=100&id=211&view=article', '675', 'Účelem testování je zjistit, kde bolest nebo dysfunkce vzniká, aby bylo možné předepsat specifickou léčbu a obnovit fyziologické vzorce pohybu sportovce. ', 'nebo, sportovce, dysfunkce, testování, při, výkonnosti, specifickou, být', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(36, 0, 'indikace-sportovni-fyzioterapie/sluzby-a-programy/pece-o-sportovce/indikace-sportovni-fyzioterapie', 'index.php?option=com_content&catid=100&id=207&view=article', '676', 'V fyzioterapeutickém centru v Horních Počernicích v Praze se specializujeme na sportovní fyzioterapii. ', 'bolesti, \r\n\r\n&nbsp, syndrom, akutní, stereotypy\r\n\r\n&nbsp, pohybové, kolena, natažení', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(37, 0, 'lecba-akutnich-urazu-sportovcu/sluzby-a-programy/pece-o-sportovce/lecba-akutnich-urazu-sportovcu', 'index.php?option=com_content&catid=100&id=208&view=article', '678', 'Cílem fyzioterapie v léčbě akutních úrazů a poranění sportovců je, aby se sportovec mohl co nejdřív vrátit ke sportovní aktivitě. ', 'léčba, \r\n\r\n&nbsp, ultrazvuk, tdp, suchou, fyzioterapie, rozsahu, měkké', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(38, 0, 'preventivni-programy-sportovcu/sluzby-a-programy/pece-o-sportovce/preventivni-programy-sportovcu', 'index.php?option=com_content&catid=100&id=209&view=article', '677', 'Ve spolupráci s fyzioterapeutem Mgr. Martinem Vojtovičem jsme v Kinisi, Praha 9 vypracovali speciální preventivní program sportovců s cvičebně-terapeutickým plánem.', 'následně, terapii, svalů, cvičení, pohybového, rámci, sekvencí, základem', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(39, 0, 'metody-a-terapeuticke-pristupy-u-sportovcu/sluzby-a-programy/pece-o-sportovce/metody-a-terapeuticke-pristupy-u-sportovcu', 'index.php?option=com_content&catid=100&id=210&view=article', '679', 'Metody a terapeutické přístupy u sportovců ve fyzioterapeutickém centru v Horních Počernicích v Praze ', 'lampou\r\n	kineziotaping\r\n\r\n\r\n\r\n\r\n\r\n	metoda, tdp, jehlou\r\n	léčba, suchou, ludmily, mojžíšové\r\n	trénink, elektroléčba, stimulace\r\n	ultrazvuk', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(40, 0, 'dynamicka-neuromuskularni-stabilizace-podle-prof-pavla-kolare-dns/metody-a-lecebne-pristupy/dynamicka-neuromuskularni-stabilizace-podle-prof-pavla-kolare-dns', 'index.php?option=com_content&catid=101&id=215&view=article', '689', 'V pražském centru fyzioterapie Kinisi využíváme koncept DNS podle Prof. Koláře (DNS) - přístup založený na vývojové kineziologii.', 'svalů, břišních, zapojení, postavení, dns, terapie, symetrii, také', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(41, 0, 'metoda-ludmily-mojzisove/metody-a-lecebne-pristupy/metoda-ludmily-mojzisove-v-nasem-fyzioterapeutickem-centru', 'index.php?option=com_content&catid=101&id=220&view=article', '692', 'Využíváme speciální manuální techniku Ludmily Mojžíšové, která vede k  odstranění chybných strukturálních a funkčních změn na pohybovém systému.', '\r\n\r\n&nbsp, při, žeber, klienta, pánevního, metody, dna, bolesti', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(42, 0, 'senzomotoricka-stimulace/metody-a-lecebne-pristupy/senzomotoricka-stimulace', 'index.php?option=com_content&catid=101&id=216&view=article', '690', 'Nácvik stability osového systému a korekce příčně i podélně ploché nohy s využitím moderních balančních pomůcek (bosu, flowin, TRX, gymball, stepper, aquahit, theraband, overball, blackroll).\r\n\r\nSenzomotorická stimulace představuje vzájemnou', 'pohybového, informací, pomůcek, při, terapii, využívá, balančních, pacienta', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(43, 0, 'integrace-primitivnich-reflexu/metody-a-lecebne-pristupy/integrace-primitivnich-reflexu', 'index.php?option=com_content&catid=101&id=217&view=article', '691', 'Za pomoci integrace primitivních reflexů dochází k upevnění a zlepšení pohybových vzorů, což napomáhá ke zlepšování motorických dovedností.', 'vývoj, reflexy, ale, jejich, jsou, psychický, pohyby, dítěte', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(44, 0, 'synergicka-reflexni-terapie-srt/metody-a-lecebne-pristupy/synergicka-reflexni-terapie-srt', 'index.php?option=com_content&catid=101&id=219&view=article', '697', 'Ve fyzioterapeutickém centru využíváme speciální manuální techniku STR vedoucí k odstranění chybných strukturálních a funkčních změn na pohybovém systému.', 'poruchy, mozková, pooperační, jako, stavy, techniky, vrozené, vady', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(45, 0, 'lecba-suchou-jehlou-dry-needling/metody-a-lecebne-pristupy/lecba-suchou-jehlou-dry-needling', 'index.php?option=com_content&catid=101&id=221&view=article', '693', 'Terapie suchou jehlou spočívá v aplikaci suché jehly do spoušťového bolestivého bodu, čímž  ve svalu dochází k výraznému analgetickému účinku.', 'bolesti, terapie, loket, bolestivé, suchou, při, aplikovat, daného', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(46, 0, 'kineziotaping/metody-a-lecebne-pristupy/vyuziti-metody-kineziotapingu', 'index.php?option=com_content&catid=101&id=222&view=article', '694', 'V pražském fyzioteraputickém centru Kinisi využíváme metodu kineziotapingu, které se dostává velké obliby ve sportovní sféře i mimo ni.', '\r\n\r\n&nbsp, bolesti, pásky, akutní, patologie, kůži, pro, oblasti', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(47, 2, 'ultrazvuk-a-elektroterapie/metody-a-lecebne-pristupy/ultrazvuk-a-elektroterapie-v-nasem-fyzickoterapeutickem-centru', 'index.php?option=com_content&catid=101&id=223&view=article', '695', 'Přístrojovou terapii využíváme pro vyhledávání a odstraňování reflexních spoušťových bodů – trigger points, posttraumatické bolesti (výrony, hematomy, zlomeniny), revmatické nebo artrotické bolesti.\r\n\r\n\r\n\r\nElektroléčba\r\n\r\nje část fyzikální terapie,', 'bolesti, &nbsp, při, vlnění, nebo, terapie, pod, aplikace', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(48, 18, 'lecba-tdp-lampou/metody-a-lecebne-pristupy/lecba-tdp-lampou-ve-fyzioterapii', 'index.php?option=com_content&catid=101&id=224&view=article', '696', 'Lampu TDT v našem fyzioterapeutickém centru Kinisi v Praze 9  využíváme především pro relaxaci svalů před mobilizací při bolestech páteře.', 'Léčba TDP lampou, akutní bolet zad terapie, akutní bolet zad léčba', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(49, 0, 'ceny-fyzioterapie-dospelych/stranky/cenik-sluzeb/fyzioterapie-dospelych', 'index.php?option=com_content&id=35&layout=theme3447:category&view=category', '639', '', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 35, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(50, 0, 'ceny-detska-fyzioterapie/stranky/cenik-sluzeb/detska-fyzioterapie', 'index.php?option=com_content&id=77&layout=theme3447:category&view=category', '640', '', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 35, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(51, 2, 'fyzioterapie-clanky-a-informace/clanky', 'index.php?option=com_content&filter_tag[0]=&id=11&layout=blog&view=category', '285', '', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 55, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(52, 0, 'fyzioterapie-praha-kontakt/website-administrators/fyzioterapeuticke-centrum-kinisi', 'index.php?option=com_contact&id=1&view=contact', '142', '\'Website Administrators\' contact category description. Ut sapien enim, rhoncus sit amet fermentum at, sagittis ac massa. Fusce quis odio sit amet ipsum gravida faucibus vel et turpis. Aliquam a dui pretium elit feugiat interdum. Suspendisse tortor', 'amet, sit, sagittis, quis, ipsum, aliquam, integer, dictum', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(53, 0, 'pozadavek-pripomenuti-jmeno/zapomenute-heslo', 'index.php?option=com_users&view=reset', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(54, 0, 'pozadavek-pripomenuti-jmeno/zapomenute-jmeno', 'index.php?option=com_users&view=remind', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(55, 0, 'pozadavek-pripomenuti-jmeno/registrace', 'index.php?option=com_users&view=registration', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(56, 0, 'kinisi-fyzioterapie-hp/kinisi/rss', 'index.php?option=com_content&format=feed&id=8&layout=theme3447:category&type=rss&view=category', '101', '', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 35, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(57, 0, 'kinisi-fyzioterapie-hp/kinisi/atom', 'index.php?option=com_content&format=feed&id=8&layout=theme3447:category&type=atom&view=category', '101', '', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 35, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(58, 0, 'kinisi-fyzioterapie-hp/clanky/posledni/svaly-okolo-kolena-by-mel-posilovat-kazdy', 'index.php?option=com_content&catid=15&id=10&view=article', '101', 'Když svaly ochabnou, kloub je náchylnější na zranění, kolena se vyplatí procvičovat.', 'jsou, břicho, kolena, které, &quot, dostat, kloubů, kondice', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(59, 17, 'kinisi-fyzioterapie-hp/clanky/posledni/fyzioterapeutuv-sen-plazovy-fotbal', 'index.php?option=com_content&catid=15&id=13&view=article', '101', 'CCC Plážový volejbal je velice prospěšný pro náš pohybový systém. ', 'bublina', '', '', NULL, '', NULL, NULL, '', '2017-12-11', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(60, 0, 'kinisi-fyzioterapie-hp/clanky/posledni/maminky-pozor-na-zatezovani-kloubu-a-svalu', 'index.php?option=com_content&catid=15&id=190&view=article', '101', 'Co dělat, aby maminky fyzicky zvládaly své mateřství? Na dotaz odpovídala Lenka Augustínová z našeho centra v Praze na servru Výhra na sedm.cz.', 'páteř, cvik, před, sebou, aby, které, ruce, mohou', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(61, 0, 'kinisi-fyzioterapie-hp/stranky/elements/fyzioterapie-sluzby-1/fyzioterapie-dospelych', 'index.php?option=com_content&catid=18&id=16&view=article', '101', 'V pražském centru Kinisi vybíráme postup léčby ze široké škály metod a terapeutických protředků individuálně podle potřeby každého klienta. ', 'pohybů, tak, aby, normalizace, obnovení, cílem, nedocházelo, přetížení', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(62, 0, 'kinisi-fyzioterapie-hp/stranky/elements/fyzioterapie-sluzby-1/detska-fyzioterapie', 'index.php?option=com_content&catid=18&id=17&view=article', '101', 'Posláním fyzioterapeutů v pražském centru Kinisi je zachytit a ovlivnit v co nejmladším věku  odchylky ve vývoji dítěte.', 'odchylky, vývoji, dítěte, ovlivnit, zachytit, fyzioterapeutů, centru, kinisi', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(63, 0, 'kinisi-fyzioterapie-hp/stranky/elements/fyzioterapie-sluzby-1/fyzioterapie-zeny', 'index.php?option=com_content&catid=18&id=167&view=article', '101', 'Zaměřujeme se na ženy toužící otěhotnět, ženy, které mají v těhotenství potíže s pohybovým aparátem nebo se chtějí udržovat v dobré fyzické kondici. ', 'také, ženy, posílit, břišní, zádové, dna, pánevního, svalů', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(64, 0, 'kinisi-fyzioterapie-hp/stranky/elements/fyzioterapie-sluzby-2/akutni-a-pooperacni-fyzioterapie', 'index.php?option=com_content&catid=73&id=18&view=article', '101', 'V Kinisi se zaměřujeme na  akutní bolesti pohybového systému a pooperační fyzioterapii ', 'fyzioterapie, akutní, bolesti, zachování, obnova, otoku, plného, pohybu', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(65, 0, 'kinisi-fyzioterapie-hp/stranky/elements/fyzioterapie-sluzby-2/funkcni-fyziotrenink', 'index.php?option=com_content&catid=73&id=166&view=article', '101', 'Naším cílem je dijít k efektivní účelné svalové aktivaci, zvýšení sportovní výkonnosti, menšímu opotřebení pohybového systému a kompenzaci stresové zátěže.', 'opotřebení, pohybového, systému, menšímu, výkonnosti, aktivaci, zvýšení, sportovní', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(66, 0, 'kinisi-fyzioterapie-hp/stranky/elements/fyzioterapie-sluzby-2/pece-o-sportovce', 'index.php?option=com_content&catid=73&id=168&view=article', '101', 'V pražském centru v Horních Počernicích se specializujeme na sportovní fyzioterapii a péčí o sportovce. ', 'analýza, vzorů, pohybových, sportovců, bezpečný, návrat, sportovce, nejrychlejší', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(67, 0, 'kinisi-fyzioterapie-hp/kinisi/slider/oteviraci-hodiny', 'index.php?option=com_content&catid=63&id=137&view=article', '101', 'Rádi Vás uvítáme v našem fyzioterapeutickém centru v Praze - Horních Počernicích\r\n\r\n\r\nDomluvit si termín', 'horních, počernicích\r\n\r\n\r\ndomluvit, termín, praze, centru, vás, uvítáme, našem', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(68, 0, 'kinisi-fyzioterapie-hp/kinisi/slider/individualni-pece', 'index.php?option=com_content&catid=63&id=138&view=article', '101', 'Každý zdravotní stav nebo zranění je individuální. Naši péči přizpůsobujeme přesně vašim potřebám.\r\n\r\n\r\nZjistit o Kinisi více', 'vašim, přesně, přizpůsobujeme, potřebám, \r\n\r\n\r\nzjistit, více, kinisi, péči', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(69, 0, 'kinisi-fyzioterapie-hp/kinisi/slider/budte-v-kondici', 'index.php?option=com_content&catid=63&id=165&view=article', '101', 'Pomůžeme vám vyřešit současný problém a zabránit jeho návratu\r\n\r\n\r\nKontaktovat', 'zabránit, jeho, návratu\r\n\r\n\r\nkontaktovat, problém, současný, vám, vyřešit, pomůžeme', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(70, 0, 'fyzioterapie-clanky-a-informace/clanky/rss', 'index.php?option=com_content&filter_tag[0]=&format=feed&id=11&layout=blog&type=rss&view=category', '285', '', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 55, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(71, 0, 'fyzioterapie-clanky-a-informace/clanky/atom', 'index.php?option=com_content&filter_tag[0]=&format=feed&id=11&layout=blog&type=atom&view=category', '285', '', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 55, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(72, 0, 'tags/media', 'index.php?option=com_tags&id=12&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(73, 0, 'tags/klouby', 'index.php?option=com_tags&id=21&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(74, 0, 'tags/svaly', 'index.php?option=com_tags&id=25&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(75, 0, 'tags/brisni-svaly', 'index.php?option=com_tags&id=22&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(76, 0, 'tags/fyzioterapie-pro-zeny', 'index.php?option=com_tags&id=19&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(77, 0, 'tags/cviceni-s-detmi', 'index.php?option=com_tags&id=20&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(78, 0, 'tags/dulezite', 'index.php?option=com_tags&id=10&view=tag', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(79, 0, 'kinisi-fyzioterapie-hp/uncategorised/kinisi-fyzioterapie-logo/upravit', 'index.php?option=com_content&a_id=144&catid=2&id=0&task=article.edit&view=article', '101', 'Centrum fyzioterapie Kinisi, Praha 9 - Horní Počernice spojuje profesionální přístup zkušených fyzioterapeutů se špičkovým moderním vybavením.', 'příjemném, prostředí, pracujeme, klienty, svými, našeho, centra, počernicích', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(80, 0, 'kinisi-fyzioterapie-hp/clanky/posledni/svaly-okolo-kolena-by-mel-posilovat-kazdy/upravit', 'index.php?option=com_content&a_id=10&catid=15&id=10&task=article.edit&view=article', '101', 'Když svaly ochabnou, kloub je náchylnější na zranění, kolena se vyplatí procvičovat.', 'jsou, břicho, kolena, které, &quot, dostat, kloubů, kondice', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(81, 6, 'kinisi-fyzioterapie-hp/clanky/posledni/fyzioterapeutuv-sen-plazovy-fotbal/upravit', 'index.php?option=com_content&a_id=13&catid=15&id=13&task=article.edit&view=article', '101', 'CCC Plážový volejbal je velice prospěšný pro náš pohybový systém. ', 'bublina', '', '', NULL, '', NULL, NULL, '', '2017-12-11', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(82, 0, 'kinisi-fyzioterapie-hp/clanky/posledni/maminky-pozor-na-zatezovani-kloubu-a-svalu/upravit', 'index.php?option=com_content&a_id=190&catid=15&id=190&task=article.edit&view=article', '101', 'Co dělat, aby maminky fyzicky zvládaly své mateřství? Na dotaz odpovídala Lenka Augustínová z našeho centra v Praze na servru Výhra na sedm.cz.', 'páteř, cvik, před, sebou, aby, které, ruce, mohou', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(83, 0, 'kinisi-fyzioterapie-hp/stranky/tym-fyzioterapie-kinisi/fyzioterapeutka-hrickova/upravit', 'index.php?option=com_content&a_id=44&catid=26&id=44&task=article.edit&view=article', '101', 'Fyzioterapeutka Kinisi, Praha 9 - Horní Počernice vedle sportovců pracuje s dospělými, dětmi od 2 let a neurologickými pacienty. ', 'studia, kde, vedené, komplexně, pacienty, zakládá, neurologickými, sportovců', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(84, 2, 'kinisi-fyzioterapie-hp/stranky/tym-fyzioterapie-kinisi/mgr-martin-vojtovic/upravit', 'index.php?option=com_content&a_id=46&catid=26&id=46&task=article.edit&view=article', '101', 'Výborný fyzioterapeut Kinisi, Praha 9 - Horní Počernice se specializuje zejména na sportovní fyzioterapii a funkční trénink.', 'Fyzioterapeut Mgr. Martin Vojtovič, Fyzioterapeut Praha 9, Fyzioterapeut Praha 8, Fyzioterapeut Horní Počernice', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(85, 0, 'kinisi-fyzioterapie-hp/stranky/tym-fyzioterapie-kinisi/fyzioterapeutka-augustinova/upravit', 'index.php?option=com_content&a_id=45&catid=26&id=45&task=article.edit&view=article', '101', 'Úspěšná fyzioterapeutka Kinisi, Praha 9 - Horní Počernice ', 'terapii, své, univerzity, její, fyzioterapie, roce, léčbě, vztahy', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(86, 14, '404/uncategorised/404', 'index.php?option=com_content&catid=2&id=65&view=article', '204', 'OMLOUVÁME SE,\r\nSTRÁNKA NEBYLA NALEZENA\r\nBohužel, stránku, na kterou jste vstoupili nemůžeme najít. \r\n\r\nVraťte se prosím na domácí stránku, zkuste vyhledávání nebo se nám rovnou ozvěte a společně najdeme to, co hledáte. S námi se možná&nbsp; dozvíte', 'jste, najít, stránku, informací, námi, než, víc, možná&nbsp', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(87, 0, '404/uncategorised/404/upravit', 'index.php?option=com_content&a_id=65&catid=2&id=65&task=article.edit&view=article', '204', 'OMLOUVÁME SE,\r\nSTRÁNKA NEBYLA NALEZENA\r\nBohužel, stránku, na kterou jste vstoupili nemůžeme najít. \r\n\r\nVraťte se prosím na domácí stránku, zkuste vyhledávání nebo se nám rovnou ozvěte a společně najdeme to, co hledáte. S námi se možná&nbsp; dozvíte', 'jste, najít, stránku, informací, námi, než, víc, možná&nbsp', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(88, 0, 'nas-tym/stranky', 'index.php?option=com_content&id=43&view=category', '701', '', '', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 35, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(89, 0, 'nas-tym/stranky/tym-fyzioterapie-kinisi', 'index.php?option=com_content&id=26&view=category', '701', '&nbsp;', '&nbsp', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 35, NULL, 1, 0, 1, 1, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(90, 2, 'pozadavek-pripomenuti-jmeno/prihlasit', 'index.php?option=com_users&view=login', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(91, 2, 'pozadavek-pripomenuti-jmeno/uzivatel/prihlasit', 'index.php?option=com_users&task=user.login', NULL, '', '', '', '', '', '', NULL, '', '', '0000-00-00', 95, NULL, 1, 0, 1, 0, '2017-12-11', 'weekly', '0.5', 0, '', 3);
INSERT INTO `bc73q_sefurls` VALUES(92, 0, 'kinisi-fyzioterapie-hp/podminky-uziti/podminky-uziti', 'index.php?option=com_content&catid=10&id=6&view=article', '101', 'Autorská práva\r\n\r\nVlastníkem a provozovatelem internetových stránek kinisi.cz je společnost Kinisi, s.r.o. Centrum fyziotarpie, která je oprávněna vykonávat majetková práva k těmto internetovým stránkám (dále jen', 'stránek, těchto, uživatel, provozovatel, stránkách, stránky, cookies, provozovatele', '', '', NULL, '', NULL, NULL, '', '0000-00-00', 15, NULL, 1, 0, 1, 1, '2017-12-12', 'weekly', '0.5', 0, '', 3);
