
-- --------------------------------------------------------

--
-- Table structure for table `bc73q_plg_easyfrontendseo`
--

DROP TABLE IF EXISTS `bc73q_plg_easyfrontendseo`;
CREATE TABLE `bc73q_plg_easyfrontendseo` (
  `id` int(11) NOT NULL,
  `url` tinytext COLLATE utf8_unicode_ci NOT NULL,
  `title` tinytext COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci NOT NULL,
  `keywords` tinytext COLLATE utf8_unicode_ci NOT NULL,
  `generator` tinytext COLLATE utf8_unicode_ci NOT NULL,
  `robots` tinytext COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `bc73q_plg_easyfrontendseo`
--

INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(1, 'index.php?option=com_content&catid=15&id=13&view=article&Itemid=101', 'Plážový volejbal z pohledu fyzioterapeuta', 'Mgr. Vojtovič z fyzioterapeutického centra v Praze 9 - Kinisi uvádí, že plážový volejbal je velice prospěšný pro náš pohybový systém.', 'Plážový volejbal, fyzio, fyzioterapie dětí Praha 9', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(4, 'index.php?option=com_content&view=form&layout=edit&a_id=13&catid=15&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kva2luaXNpLWZ5emlvdGVyYXBpZS1ocC9jbGFua3kvcG9zbGVkbmkvZnl6aW90ZXJhcGV1dHV2LXNlbi1wbGF6b3Z5LWZvdGJhbA==&Itemid=101', 'Domů', 'Kinisi Centrum fyzioterapie, Praha 9 - Diagnostika a léčba poruch pohybového systému, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Centrum fyzioterapie, fyzioterapie Praha 9, fyzioterapeut Praha, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(5, 'index.php?option=com_content&catid=15&id=10&view=article&Itemid=101', 'Svaly kolem kolena by měl posilovat každý', 'XXX Když svaly ochabnou, kloub je náchylnější na zranění, kolena se vyplatí procvičovat.', 'Centrum fyzioterapie, fyzioterapie Praha 9, fyzioterapeut Praha, dětský fyzioterapeut ', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(6, 'index.php?option=com_content&catid=15&id=190&view=article&Itemid=101', '{div class=__ARKQUOTE__editable__ARKQUOTE__ data-id=__ARKQUOTE__190__ARKQUOTE__ data-context=__ARKQUOTE__article__ARKQUOTE__ data-type=__ARKQUOTE__title__ARKQUOTE__ data-itemtype=__ARKQUOTE__article__ARKQUOTE__ contenteditable=__ARKQUOTE__true__ARKQUOTE__', 'Co dělat, aby maminky fyzicky zvládaly své mateřství? Na dotaz odpovídala Lenka Augustínová z našeho centra v Praze na servru Výhra na sedm.cz.', 'Centrum fyzioterapie, fyzioterapie Praha 9, fyzioterapeut Praha, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(7, 'index.php?option=com_content&catid=26&id=44&view=article&Itemid=701', '{div class=__ARKQUOTE__editable__ARKQUOTE__ data-id=__ARKQUOTE__44__ARKQUOTE__ data-context=__ARKQUOTE__article__ARKQUOTE__ data-type=__ARKQUOTE__title__ARKQUOTE__ data-itemtype=__ARKQUOTE__article__ARKQUOTE__ contenteditable=__ARKQUOTE__true__ARKQUOTE__ ', 'Fyzioterapeutka Kinisi, Praha 9 - Horní Počernice vedle sportovců pracuje s dospělými, dětmi od 2 let a neurologickými pacienty. ', 'Tým Kinisi Centrum Fyzioterapie, společnost fyzioterapie Praha 9 Horní Počernice, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(8, 'index.php?option=com_content&catid=26&id=45&view=article&Itemid=701', 'Mgr. Lenka Augustínová', 'Úspěšná fyzioterapeutka poskytující služby fyzioterapeuta v Kinisi, Praha 9 - Horní Počernice ', 'Tým Kinisi Centrum Fyzioterapie, společnost fyzioterapie Praha 9 Horní Počernice, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(9, 'index.php?option=com_content&id=9&layout=theme3447:category&view=category&Itemid=134', 'O nás', 'O společnosti Kinisi centrum fyzioterapie se sídlem Praha 9 Horní Počernice - soukromý fyzioterapeut', 'služby fizioterapeuta, fyzioterapeut Praha Horní Počernice', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(10, 'index.php?option=com_content&id=67&layout=theme3447:category&view=category&Itemid=701', 'Náš tým', 'Tým Kinisi centrum fyzioterapie se sídlem Praha 9 Horní Počernice', 'Tým Kinisi Centrum Fyzioterapie, společnost fyzioterapie Praha 9 Horní Počernice, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(11, 'index.php?option=com_contact&id=1&view=contact&Itemid=142', 'Kontakt', 'Kontakt Kinisi centrum fyzioterapie Praha 9, špičkoví fyzioterapeuti - soukromá dětská, dospělá a sportovní fyzioterapie', 'sportovní fyzioterapie Praha 9,dětská fyzioterapie Praha 9,kontakt fyzioterapie Praha 9, dospělé fyzio', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(12, 'index.php?option=com_content&catid=84&id=192&view=article&Itemid=656', 'Vyšetření', 'Používané metody a terapeutické přístupy ve fyzioterapii dospělých v centru fyzioterapie Praha 9', 'výborný fyzioterapeut Praha, fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(13, 'index.php?option=com_content&view=form&layout=edit&a_id=192&catid=84&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvdnlzZXRyZW5pL3NsdXpieS1hLXByb2dyYW15L2Z5emlvdGVyYXBpZS1kb3NwZWx5Y2gvZnl6aW90ZXJhcGV1dGlja2UtdnlzZXRyZW5pLWRvc3BlbHljaA==&Itemid=656', 'Vyšetření', 'Fyzioterapeutické centrum Kinisi, Praha 9, Horní Počernice - vyšetření ve fyzioterapii dospělých', 'fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(14, 'index.php?option=com_content&catid=83&id=227&view=article&Itemid=681', 'Základní informace', 'V pražském centru Kinisi vybíráme postup léčby ze široké škály metod a terapeutických prostředků individuálně podle potřeby každého klienta. ', 'fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(15, 'index.php?option=com_content&catid=101&id=215&view=article&Itemid=689', 'Dynamická neuromuskulární stabilizace (DNS)', 'V pražském centru fyzioterapie Kinisi využíváme koncept DNS podle Prof. Koláře (DNS) - přístup založený na vývojové kineziologii.', 'fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(16, 'index.php?option=com_content&id=35&layout=theme3447:category&view=category&Itemid=639', 'Ceny fyzioterapie dospělých - Fyzioteraputické centrum KINISI', 'Fyzioteraputické centrum KINISI, Praha 9, Horní Počernice, špičkoví fyzioterapeuti, fyzioterapie pro dospělé a děti, péče o sportovce, fukční trénink - ceny', 'ceny služeb fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(17, 'index.php?option=com_content&view=form&layout=edit&a_id=184&catid=35&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvY2VueS1meXppb3RlcmFwaWUtZG9zcGVseWNoL3N0cmFua3kvY2VuaWstc2x1emViL2Z5emlvdGVyYXBpZS1kb3NwZWx5Y2g=&Itemid=639', 'Ceny fyzioterapie dospělých - Fyzioteraputické centrum KINISI', 'Ceny služeb Fyzioterapeutické centrum KINISI, Praha 9, Horní Počernice, špičkoví fyzioterapeuti, fyzioterapie pro dospělé a děti, sportovce, funkční trénink', 'fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(18, 'index.php?option=com_content&view=form&layout=edit&a_id=182&catid=35&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvY2VueS1meXppb3RlcmFwaWUtZG9zcGVseWNoL3N0cmFua3kvY2VuaWstc2x1emViL2Z5emlvdGVyYXBpZS1kb3NwZWx5Y2g=&Itemid=639', 'Ceny fyzioterapie dospělých - Fyzioteraputické centrum KINISI', 'Ceny služeb Fyzioterapeutické centrum Praha 9, Horní Počernice, špičkoví fyzioterapeuti, fyzioterapie pro dospělé a děti, péče o sportovce, funkční trénink', 'ceny fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(19, 'index.php?option=com_content&view=form&layout=edit&a_id=227&catid=83&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvemFrbGFkbmktaW5mb3JtYWNlL3NsdXpieS1hLXByb2dyYW15L2Z5emlvdGVyYXBpZS1kb3NwZWx5Y2gtemFrbGFkbmktaW5mbw==&Itemid=681', 'Základní informace - Fyzioteraputické centrum KINISI', 'Fyzioterapeutické centrum Kinisi, Praha 9 - Horní Počernice - fyzioterapie dospělých', 'fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(22, 'index.php?option=com_content&view=form&layout=edit&a_id=144&catid=2&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kv&Itemid=101', 'Domů - Fyzioteraputické centrum KINISI', 'Kinisi Centrum fyzioterapie, Praha 9 - Diagnostika a léčba poruch pohybového systému, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Centrum fyzioterapie, fyzioterapie Praha 9, fyzioterapeut Praha, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(27, 'index.php?option=com_content&view=form&layout=edit&a_id=194&Itemid=658&catid=84&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvbWV0b2R5LWEtdGVyYXBldXRpY2tlLXByaXN0dXB5L3NsdXpieS1hLXByb2dyYW15L2Z5emlvdGVyYXBpZS1kb3NwZWx5Y2gvbWV0b2R5LWEtdGVyYXBldXRpY2tlLXByaXN0dXB5', 'Metody a terapeutické přístupy', 'Fyzioterapeutické centrum Kinisi, Praha 9, Horní Počernice - metody a terapeutické přístupy ve fyzioterapii dospělých', 'fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(28, 'index.php?option=com_content&view=form&layout=edit&a_id=194&Itemid=658&catid=84&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvbWV0b2R5LWEtdGVyYXBldXRpY2tlLXByaXN0dXB5L3NsdXpieS1hLXByb2dyYW15L2Z5emlvdGVyYXBpZS1kb3NwZWx5Y2gvbWV0b2R5LWEtdGVyYXBldXRpY2tlLXByaXN0dXB5', 'Metody a terapeutické přístupy', 'Fyzioterapeutické centrum Kinisi, Praha 9, Horní Počernice - metody a terapeutické přístupy ve fyzioterapii dospělých', 'fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(30, 'index.php?option=com_content&view=form&layout=edit&a_id=194&Itemid=658&catid=84&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvbWV0b2R5LWEtdGVyYXBldXRpY2tlLXByaXN0dXB5L3NsdXpieS1hLXByb2dyYW15L2Z5emlvdGVyYXBpZS1kb3NwZWx5Y2gvbWV0b2R5LWEtdGVyYXBldXRpY2tlLXByaXN0dXB5', 'Metody a terapeutické přístupy', 'Fyzioterapeutické centrum Kinisi, Praha 9, Horní Počernice - metody a terapeutické přístupy ve fyzioterapii dospělých', 'fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(31, 'index.php?option=com_content&view=form&layout=edit&a_id=193&catid=84&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvaW5kaWthY2Uvc2x1emJ5LWEtcHJvZ3JhbXkvZnl6aW90ZXJhcGllLWRvc3BlbHljaC9pbmRpa2FjZQ==&Itemid=657', 'Indikace - Fyzioteraputické centrum KINISI', 'Fyzioterapeutické centrum Kinisi, Praha 9, Horní Počernice - indikace ve fyzioterapii dospělých', 'fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(32, 'index.php?option=com_content&catid=84&id=193&view=article&Itemid=657', 'Indikace - Fyzioteraputické centrum KINISI', 'Používané metody a terapeutické přístupy ve fyzioterapii dospělých v centru', 'akutní bolet zad terapie, akutní bolet zad léčba,co mi pomůže na bolest zad', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(33, 'index.php?option=com_content&catid=2&id=65&view=article&Itemid=204', '404 stránka - Fyzioteraputické centrum KINISI', 'OMLOUVÁME SE,\r\nSTRÁNKA NEBYLA NALEZENA\r\nBohužel, stránku, na kterou jste vstoupili nemůžeme najít. \r\n\r\nVraťte se prosím na domácí stránku, zkuste vyhledávání nebo se nám rovnou ozvěte a společně najdeme to, co hledáte. S námi se možná&nbsp; dozvíte', 'jste, najít, stránku, informací, námi, než, víc, možná&nbsp', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(34, 'index.php?option=com_content&view=category&layout=theme3447:category&id=8&Itemid=101', 'Domů - Fyzioteraputické centrum KINISI', 'Kinisi Centrum fyzioterapie, Praha 9 - Diagnostika a léčba poruch pohybového systému, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Centrum fyzioterapie, fyzioterapie Praha 9, fyzioterapeut Praha, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(35, 'index.php?option=com_content&view=form&layout=edit&a_id=10&catid=15&return=aHR0cDovLzg5LjE3Ny40My42OS9raW5pc2kva2luaXNpLWZ5emlvdGVyYXBpZS1ocC9jbGFua3kvcG9zbGVkbmkvc3ZhbHktb2tvbG8ta29sZW5hLWJ5LW1lbC1wb3NpbG92YXQta2F6ZHk=&Itemid=101', 'Domů', 'Kinisi Centrum fyzioterapie, Praha 9 - Diagnostika a léčba poruch pohybového systému, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Centrum fyzioterapie, fyzioterapie Praha 9, fyzioterapeut Praha, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(36, 'index.php?option=com_content&id=10&layout=theme3447:category&view=category&Itemid=176', 'Ochrana soukromí', 'Podmínky užití - Fyzioteraputické centrum KINISI, Praha 9, Horní Počernice, špičkoví fyzioterapeuti, fyzioterapie pro dospělé a děti, péče o sportovce', 'podmínlky užití, fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(37, 'index.php?option=com_content&view=form&layout=edit&a_id=6&catid=10&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvb2NocmFuYS1zb3Vrcm9taS9wb2RtaW5reS11eml0aQ==&Itemid=176', 'Ochrana soukromí', 'Podmínky užití - fyzioteraputické centrum KINISI, Praha 9, Horní Počernice, špičkoví fyzioterapeuti, fyzioterapie pro dospělé a děti, péče o sportovce, ', 'fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(38, 'index.php?option=com_config&controller=config.display.modules&id=244&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kv', 'Fyzioteraputické centrum KINISI', 'Fyzioteraputické centrum KINISI, Praha 9, Horní Počernice, špičkoví fyzioterapeuti, fyzioterapie pro dospělé a děti, péče o sportovce, fukční trénink', 'fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(39, 'index.php?option=com_content&view=form&layout=edit&a_id=155&catid=9&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvY2VudHJ1bS1meXppb3RlcmFwaWUtcHJhaGEvby1uYXM=&Itemid=134', 'O nás', 'O společnosti Kinisi Centrum Fyzioterapie se sídlem Praha 9 Horní Počernice', 'O společnosti Kinisi Centrum Fyzioterapie, společnost fyzioterapie Praha 9 Horní Počernice, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(40, 'index.php?option=com_content&view=form&layout=edit&a_id=157&catid=71&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvY2VudHJ1bS1meXppb3RlcmFwaWUtcHJhaGEvby1uYXM=&Itemid=134', 'O nás', 'O společnosti Kinisi Centrum Fyzioterapie se sídlem Praha 9 Horní Počernice', 'O společnosti Kinisi Centrum Fyzioterapie, společnost fyzioterapie Praha 9 Horní Počernice, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(41, 'index.php?option=com_content&view=form&layout=edit&a_id=163&catid=72&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvY2VudHJ1bS1meXppb3RlcmFwaWUtcHJhaGEvby1uYXM=&Itemid=134', 'O nás', 'O společnosti Kinisi Centrum Fyzioterapie se sídlem Praha 9 Horní Počernice', 'O společnosti Kinisi Centrum Fyzioterapie, společnost fyzioterapie Praha 9 Horní Počernice, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(42, 'index.php?option=com_content&view=form&layout=edit&a_id=159&catid=69&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvY2VudHJ1bS1meXppb3RlcmFwaWUtcHJhaGEvby1uYXM=&Itemid=134', 'O nás', 'O společnosti Kinisi Centrum Fyzioterapie se sídlem Praha 9 Horní Počernice', 'O společnosti Kinisi Centrum Fyzioterapie, společnost fyzioterapie Praha 9 Horní Počernice, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(43, 'index.php?option=com_content&view=form&layout=edit&a_id=158&catid=70&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvY2VudHJ1bS1meXppb3RlcmFwaWUtcHJhaGEvby1uYXM=&Itemid=134', 'O nás', 'O společnosti Kinisi Centrum Fyzioterapie se sídlem Praha 9 Horní Počernice', 'O společnosti Kinisi Centrum Fyzioterapie, společnost fyzioterapie Praha 9 Horní Počernice, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(44, 'index.php?option=com_content&catid=84&id=194&view=article&Itemid=658', 'Metody a terapeutické přístupy', 'Používané metody a terapeutické přístupy ve fyzioterapii dospělých v centru fyzioterapie Kinisi na Praze 9', 'fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(45, 'index.php?option=com_content&view=form&layout=edit&a_id=194&catid=84&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvbWV0b2R5LWEtdGVyYXBldXRpY2tlLXByaXN0dXB5L3NsdXpieS1hLXByb2dyYW15L2Z5emlvdGVyYXBpZS1kb3NwZWx5Y2gvbWV0b2R5LWEtdGVyYXBldXRpY2tlLXByaXN0dXB5LXZlLWZ5eml', 'Metody a terapeutické přístupy', 'Fyzioterapeutické centrum Kinisi, Praha 9, Horní Počernice - metody a terapeutické přístupy ve fyzioterapii dospělých', 'fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(46, 'index.php?option=com_content&view=form&layout=edit&a_id=215&catid=101&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvZHluYW1pY2thLW5ldXJvbXVza3VsYXJuaS1zdGFiaWxpemFjZS1wb2RsZS1wcm9mLXBhdmxhLWtvbGFyZS1kbnMvbWV0b2R5LWEtbGVjZWJuZS1wcmlzdHVweS9keW5hbWlja2EtbmV1cm9tdX', 'Dynamická neuromuskulární stabilizace (DNS)', 'Ve fyzioterapeutickém centru Kinisi, Praha 9, Horní Počernice využíváme metodu Dynamická neuromuskulární stabilizace (DNS)', 'fyzioterapie Praha 9, dětská fyzioterapie, funkční trénink, sportovní fyzioterapie, péče o sportovce, fyzioterapie pro ženy', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(47, 'index.php?option=com_content&filter_tag[0]=&id=11&layout=blog&view=category&Itemid=285', 'Články', 'Články a informace Kinisi Centrum Fyzioterapie', 'novinky fyzioterapie, články fyzioterapie, fyzioterapie na Praze 9, fyzioterapeut Praha články, fyzioterapie zajímavosti', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(48, 'index.php?option=com_content&view=form&layout=edit&a_id=10&catid=15&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kva2luaXNpLWZ5emlvdGVyYXBpZS1ocC9jbGFua3kvcG9zbGVkbmkvc3ZhbHktb2tvbG8ta29sZW5hLWJ5LW1lbC1wb3NpbG92YXQta2F6ZHk=&Itemid=101', 'Domů', 'Kinisi Centrum fyzioterapie, Praha 9 - Diagnostika a léčba poruch pohybového systému, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Centrum fyzioterapie, fyzioterapie Praha 9, fyzioterapeut Praha, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(49, 'index.php?option=com_content&view=form&layout=edit&a_id=44&catid=26&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kva2luaXNpLWZ5emlvdGVyYXBpZS1ocC9jbGFua3kvcG9zbGVkbmkvc3ZhbHktb2tvbG8ta29sZW5hLWJ5LW1lbC1wb3NpbG92YXQta2F6ZHk=&Itemid=101', 'Domů', 'Kinisi Centrum fyzioterapie, Praha 9 - Diagnostika a léčba poruch pohybového systému, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Centrum fyzioterapie, fyzioterapie Praha 9, fyzioterapeut Praha, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Joomla! - Open Source Content Management', 'index, follow');
INSERT INTO `bc73q_plg_easyfrontendseo` VALUES(50, 'index.php?option=com_content&view=form&layout=edit&a_id=44&catid=26&return=aHR0cDovL2xvY2FsaG9zdC9raW5pc2kvbmFzLXR5bS9zdHJhbmt5L3R5bS1meXppb3RlcmFwaWUta2luaXNpL2Z5emlvdGVyYXBldXRrYS1ocmlja292YQ==&Itemid=101', 'Domů', 'Kinisi Centrum fyzioterapie, Praha 9 - Diagnostika a léčba poruch pohybového systému, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Centrum fyzioterapie, fyzioterapie Praha 9, fyzioterapeut Praha, dětský fyzioterapeut Praha, sportovní fyzioterapeut Praha, fyzioterapie v těhotenství a po porodu, dětská fyzioterapie, sportovní fyzioterapie ', 'Joomla! - Open Source Content Management', 'index, follow');
